const STORAGE_KEY = "workflow-canvas-communication-draft-v1";
const LEGACY_STORAGE_KEY = "workflow-canvas-legal-blueprint-v1";
const ZOOM_MIN = 0.01;
const ZOOM_MAX = 2.2;
const ZOOM_CLICK_IN = 0.05;
const ZOOM_CLICK_OUT_COARSE = 0.05;
const ZOOM_CLICK_OUT_FINE = 0.01;
const ZOOM_FINE_THRESHOLD = 0.1;
const AUTOSAVE_DELAY_MS = 600;
const DISCUSSION_MARKERS = ["待讨论", "已决定", "有疑问", "不采用"];
const NODE_DEFAULTS = {
  rect: { label: "步骤", note: "双击编辑文字" }, diamond: { label: "判断", note: "条件分支" }, circle: { label: "开始 / 结束", note: "" }, document: { label: "材料", note: "来源或文档" }, triangle: { label: "提醒", note: "需要处理" }, text: { label: "输入文字", note: "" },
};
const NODE_TYPE_LABELS = { rect: "步骤（矩形）", diamond: "判断（菱形）", circle: "开始 / 结束（圆形）", document: "材料（文档形）", triangle: "提醒（三角形）", text: "文字" };
const RESIZE_HANDLES_BY_TYPE = {
  rect: ["nw", "ne", "se", "sw"],
  document: ["nw", "ne", "se", "sw"],
  text: ["nw", "ne", "se", "sw"],
  diamond: ["n", "e", "s", "w"],
  circle: ["n", "e", "s", "w"],
  triangle: ["n", "se", "sw"],
};
const NODE_MIN_SIZES = { rect: { w: 120, h: 92 }, document: { w: 120, h: 92 }, diamond: { w: 76, h: 76 }, circle: { w: 76, h: 76 }, triangle: { w: 96, h: 84 }, text: { w: 80, h: 40 } };
const viewport = document.querySelector("#viewport"), surface = document.querySelector("#surface"), nodeLayer = document.querySelector("#nodeLayer"), edgeGroup = document.querySelector("#edges"), temporaryEdge = document.querySelector("#temporaryEdge"), canvasTabs = document.querySelector("#canvasTabs"), importInput = document.querySelector("#importInput"), saveStatus = document.querySelector("#saveStatus"), selectionStatus = document.querySelector("#selectionStatus"), statusDot = document.querySelector("#statusDot"), zoomValue = document.querySelector("#zoomValue"), selectionHint = document.querySelector("#selectionHint"), toast = document.querySelector("#toast"), inspector = document.querySelector("#nodeInspector"), inspectorEmpty = document.querySelector("#inspectorEmpty"), inspectorForm = document.querySelector("#inspectorForm"), inspectorCount = document.querySelector("#inspectorCount"), inspectorName = document.querySelector("#inspectorName"), inspectorNote = document.querySelector("#inspectorNote"), inspectorType = document.querySelector("#inspectorType"), inspectorMarker = document.querySelector("#inspectorMarker"), previousNodes = document.querySelector("#previousNodes"), nextNodes = document.querySelector("#nextNodes"), previousCount = document.querySelector("#previousCount"), nextCount = document.querySelector("#nextCount");
let state = loadState(), activeTool = "select", selectedNodeId = null, resizeModeNodeId = null, selectedEdgeId = null, connectorSourceId = null, history = [], future = [], drag = null, resizing = null, pan = null, connecting = null, editing = null, inspectorEdit = null, toastTimer, autosaveTimer = null, isDirty = false;

function createId(prefix) { return `${prefix}-${globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`}`; }
function defaultState() { return { version: 1, activeCanvasId: "canvas-main", canvases: [{ id: "canvas-main", name: "产品逻辑草图", nodes: [{ id: "node-source", type: "document", x: 50, y: 300, w: 176, h: 92, label: "收集材料", note: "把已有信息放到一起", marker: "已决定" }, { id: "node-analysis", type: "diamond", x: 280, y: 282, w: 112, h: 112, label: "形成判断", note: "这里需要讨论依据", marker: "待讨论" }, { id: "node-review", type: "rect", x: 470, y: 300, w: 176, h: 92, label: "共同核对", note: "人与 AI 一起检查", marker: "有疑问" }, { id: "node-publish", type: "document", x: 680, y: 300, w: 176, h: 92, label: "整理结论", note: "形成下一步沟通材料", marker: "待讨论" }], edges: [{ id: "edge-1", from: "node-source", to: "node-analysis" }, { id: "edge-2", from: "node-analysis", to: "node-review" }, { id: "edge-3", from: "node-review", to: "node-publish" }], view: { zoom: 1, panX: 0, panY: 0 } }] }; }
function clampZoom(value) { return Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, Number.isFinite(value) ? value : 1)); }
function minSizeForType(type) { return NODE_MIN_SIZES[type] || NODE_MIN_SIZES.rect; }
function normalizeNode(node) { if (!node || typeof node.id !== "string") return null; const type = NODE_DEFAULTS[node.type] ? node.type : "rect", d = NODE_DEFAULTS[type], minimum = minSizeForType(type), fallbackW = type === "diamond" || type === "circle" ? 112 : type === "text" ? 150 : type === "triangle" ? 126 : 176, fallbackH = type === "diamond" || type === "circle" ? 112 : type === "text" ? 48 : type === "triangle" ? 112 : 92, marker = typeof node.marker === "string" && DISCUSSION_MARKERS.includes(node.marker.trim()) ? node.marker.trim() : "待讨论"; return { id: node.id, type, x: Number.isFinite(node.x) ? node.x : 240, y: Number.isFinite(node.y) ? node.y : 240, w: Math.max(minimum.w, Number.isFinite(node.w) ? node.w : fallbackW), h: Math.max(minimum.h, Number.isFinite(node.h) ? node.h : fallbackH), label: typeof node.label === "string" ? node.label.trim() || "未命名节点" : d.label, note: typeof node.note === "string" ? node.note.trim() : d.note, marker }; }
function normalizeState(input) { if (!input || !Array.isArray(input.canvases) || !input.canvases.length) return defaultState(); const canvases = input.canvases.map((canvas, i) => ({ id: typeof canvas.id === "string" ? canvas.id : createId("canvas"), name: typeof canvas.name === "string" && canvas.name.trim() ? canvas.name.trim() : `工作流 ${i + 1}`, nodes: Array.isArray(canvas.nodes) ? canvas.nodes.map(normalizeNode).filter(Boolean) : [], edges: Array.isArray(canvas.edges) ? canvas.edges.filter((e) => e && typeof e.from === "string" && typeof e.to === "string").map((e) => ({ id: e.id || createId("edge"), from: e.from, to: e.to })) : [], view: { zoom: clampZoom(canvas.view?.zoom), panX: Number.isFinite(canvas.view?.panX) ? canvas.view.panX : 0, panY: Number.isFinite(canvas.view?.panY) ? canvas.view.panY : 0 } })); return { version: 1, activeCanvasId: canvases.some((c) => c.id === input.activeCanvasId) ? input.activeCanvasId : canvases[0].id, canvases }; }
function loadState() { try { const current = localStorage.getItem(STORAGE_KEY), legacy = current ? null : localStorage.getItem(LEGACY_STORAGE_KEY), saved = current || legacy; if (!saved) return defaultState(); const normalized = normalizeState(JSON.parse(saved)); if (legacy) { localStorage.setItem(STORAGE_KEY, JSON.stringify(normalized)); localStorage.removeItem(LEGACY_STORAGE_KEY); } return normalized; } catch { return defaultState(); } }
function hasSavedDraft() { try { return Boolean(localStorage.getItem(STORAGE_KEY) || localStorage.getItem(LEGACY_STORAGE_KEY)); } catch { return false; } }
function activeCanvas() { return state.canvases.find((c) => c.id === state.activeCanvasId) || state.canvases[0]; }
function snapshot() { return JSON.parse(JSON.stringify(state)); }
function render() { renderTabs(); renderNodes(); renderEdges(); renderTransform(); renderInspector(); updateStatus(); }
function renderTabs() { canvasTabs.innerHTML = ""; state.canvases.forEach((canvas) => { const tab = document.createElement("div"); tab.className = `canvas-tab${canvas.id === state.activeCanvasId ? " is-active" : ""}`; tab.dataset.canvasId = canvas.id; tab.innerHTML = `<span class="tab-label"></span><button class="tab-close" title="关闭画布" aria-label="关闭画布">×</button>`; tab.querySelector(".tab-label").textContent = canvas.name; canvasTabs.append(tab); }); const add = document.createElement("button"); add.className = "new-tab"; add.dataset.action = "new-canvas"; add.title = "新建画布"; add.textContent = "+"; canvasTabs.append(add); }
function markerClass(marker) { return `marker-${DISCUSSION_MARKERS.indexOf(marker) >= 0 ? DISCUSSION_MARKERS.indexOf(marker) : 0}`; }
function resizeHandlesForNode(node) { return RESIZE_HANDLES_BY_TYPE[node.type] || RESIZE_HANDLES_BY_TYPE.rect; }
function resizeHandlePositions(node) { return { nw: [node.x - 5, node.y - 5], n: [node.x + node.w / 2 - 5, node.y - 19], ne: [node.x + node.w - 5, node.y - 5], e: [node.x + node.w + 9, node.y + node.h / 2 - 5], se: [node.x + node.w - 5, node.y + node.h - 5], s: [node.x + node.w / 2 - 5, node.y + node.h + 9], sw: [node.x - 5, node.y + node.h - 5], w: [node.x - 19, node.y + node.h / 2 - 5] }; }
function renderResizeHandles(node) { if (!node || activeTool !== "select" || resizeModeNodeId !== node.id) return; const positions = resizeHandlePositions(node); resizeHandlesForNode(node).forEach((handle) => { const el = document.createElement("div"); el.className = `resize-handle resize-${handle}`; el.dataset.nodeId = node.id; el.dataset.handle = handle; el.title = "调整节点大小"; el.style.left = `${positions[handle][0]}px`; el.style.top = `${positions[handle][1]}px`; nodeLayer.append(el); }); }
function renderNodes() { nodeLayer.innerHTML = ""; const canvas = activeCanvas(); canvas.nodes.forEach((node) => { const minimum = minSizeForType(node.type), isSelected = selectedNodeId === node.id, isResizeMode = resizeModeNodeId === node.id, el = document.createElement("div"); el.className = `node shape-${node.type}${isSelected ? " is-selected" : ""}${connectorSourceId === node.id ? " is-connecting" : ""}`; el.dataset.nodeId = node.id; el.style.left = `${node.x}px`; el.style.top = `${node.y}px`; el.style.width = `${Math.max(node.w, minimum.w)}px`; el.style.minHeight = `${Math.max(node.h, minimum.h)}px`; el.innerHTML = `<div class="node-content"><span class="node-label"></span><span class="node-note"></span><span class="node-marker"></span></div><button class="resize-toggle${isResizeMode ? " is-active" : ""}" type="button" data-node-id="${node.id}" title="${isResizeMode ? "隐藏尺寸控制点" : "显示尺寸控制点"}" aria-label="${isResizeMode ? "隐藏尺寸控制点" : "显示尺寸控制点"}" aria-pressed="${isResizeMode}"><span aria-hidden="true">⤢</span></button><span class="port" data-side="top" title="从上方连接"></span><span class="port" data-side="right" title="从右侧连接"></span><span class="port" data-side="bottom" title="从下方连接"></span><span class="port" data-side="left" title="从左侧连接"></span>`; el.querySelector(".node-label").textContent = node.label; el.querySelector(".node-note").textContent = node.note; el.querySelector(".node-marker").textContent = node.marker; el.querySelector(".node-marker").classList.add(markerClass(node.marker)); if (!node.note) el.querySelector(".node-note").hidden = true; el.querySelector(".resize-toggle").hidden = !isSelected; nodeLayer.append(el); }); renderResizeHandles(canvas.nodes.find((node) => node.id === selectedNodeId)); document.querySelector("#canvasEmpty").hidden = canvas.nodes.length > 0; }
function relationNodes(nodeId, direction) { const canvas = activeCanvas(), ids = canvas.edges.filter((edge) => direction === "previous" ? edge.to === nodeId : edge.from === nodeId).map((edge) => direction === "previous" ? edge.from : edge.to); return ids.map((id) => canvas.nodes.find((node) => node.id === id)).filter(Boolean); }
function renderRelationList(container, nodes, emptyText) { container.innerHTML = ""; if (!nodes.length) { const empty = document.createElement("span"); empty.className = "relation-empty"; empty.textContent = emptyText; container.append(empty); return; } nodes.forEach((node) => { const button = document.createElement("button"); button.type = "button"; button.className = "relation-item"; button.dataset.inspectNodeId = node.id; button.title = `选择${node.label}`; button.textContent = node.label; container.append(button); }); }
function renderInspector() { const node = activeCanvas().nodes.find((item) => item.id === selectedNodeId); inspectorEmpty.hidden = Boolean(node); inspectorForm.hidden = !node; inspectorCount.textContent = node ? "1 个节点" : "未选择"; if (!node) return; inspectorName.value = node.label; inspectorNote.value = node.note; inspectorType.value = NODE_TYPE_LABELS[node.type] || node.type; inspectorMarker.value = DISCUSSION_MARKERS.includes(node.marker) ? node.marker : "待讨论"; const previous = relationNodes(node.id, "previous"), next = relationNodes(node.id, "next"); previousCount.textContent = String(previous.length); nextCount.textContent = String(next.length); renderRelationList(previousNodes, previous, "无前置节点"); renderRelationList(nextNodes, next, "无后续节点"); }
function anchorBetween(node, other) { const cx = node.x + node.w / 2, cy = node.y + node.h / 2, dx = other.x + other.w / 2 - cx, dy = other.y + other.h / 2 - cy; if (Math.abs(dx) > Math.abs(dy)) return { x: dx >= 0 ? node.x + node.w : node.x, y: cy }; return { x: cx, y: dy >= 0 ? node.y + node.h : node.y }; }
function curvePath(x1, y1, x2, y2) { const bend = Math.max(50, Math.abs(x2 - x1) * .38), direction = x2 >= x1 ? 1 : -1; return `M ${x1} ${y1} C ${x1 + bend * direction} ${y1}, ${x2 - bend * direction} ${y2}, ${x2} ${y2}`; }
function renderEdges() { edgeGroup.innerHTML = ""; const canvas = activeCanvas(); canvas.edges.forEach((edge) => { const from = canvas.nodes.find((n) => n.id === edge.from), to = canvas.nodes.find((n) => n.id === edge.to); if (!from || !to) return; const a = anchorBetween(from, to), b = anchorBetween(to, from), path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.classList.add("edge"); if (selectedEdgeId === edge.id) path.classList.add("is-selected"); path.dataset.edgeId = edge.id; path.setAttribute("d", curvePath(a.x, a.y, b.x, b.y)); edgeGroup.append(path); }); }
function renderTransform() { const view = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; surface.style.transform = `translate(${view.panX}px, ${view.panY}px) scale(${view.zoom})`; zoomValue.textContent = `${Math.round(view.zoom * 100)}%`; }
function updateStatus() { const node = activeCanvas().nodes.find((n) => n.id === selectedNodeId); selectionStatus.textContent = node ? `已选择：${node.label}` : selectedEdgeId ? "已选择：连线" : "未选择节点"; selectionHint.hidden = !node; if (node) selectionHint.textContent = `${node.label} · 点击右上角缩放图标，再拖动控制点调整大小；拖动圆点连接`; }
function commit(mutator, message = "已更新") { history.push(snapshot()); if (history.length > 80) history.shift(); future = []; mutator(); render(); saveLocal(message); }
function saveLocal(message = "已保存到本机") { clearTimeout(autosaveTimer); autosaveTimer = null; try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); saveStatus.textContent = message; statusDot.classList.remove("is-dirty"); isDirty = false; return true; } catch { saveStatus.textContent = message === "已自动保存" ? "自动保存失败" : "保存失败"; statusDot.classList.add("is-dirty"); isDirty = true; return false; } }
function markDirty() { isDirty = true; saveStatus.textContent = "有未保存改动"; statusDot.classList.add("is-dirty"); clearTimeout(autosaveTimer); autosaveTimer = setTimeout(() => { autosaveTimer = null; saveLocal("已自动保存"); }, AUTOSAVE_DELAY_MS); }
function flushPendingSave() { if (isDirty || autosaveTimer) saveLocal("已保存到本机"); }
function showToast(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add("is-visible"); toastTimer = setTimeout(() => toast.classList.remove("is-visible"), 1900); }
function setTool(tool) { activeTool = tool; connectorSourceId = null; document.querySelectorAll(".tool-button").forEach((b) => b.classList.toggle("is-active", b.dataset.tool === tool)); showToast(tool === "select" ? "选择工具" : tool === "connector" ? "连接工具：点击两个节点或拖动端点" : "在画布空白处放置节点"); }
function screenToWorld(x, y) { const r = viewport.getBoundingClientRect(), view = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; return { x: (x - r.left - view.panX) / view.zoom, y: (y - r.top - view.panY) / view.zoom }; }
function addNode(type, x, y) { const p = screenToWorld(x, y), d = NODE_DEFAULTS[type], size = type === "diamond" || type === "circle" ? { w: 112, h: 112 } : type === "text" ? { w: 150, h: 48 } : type === "triangle" ? { w: 126, h: 112 } : { w: 176, h: 92 }, node = { id: createId("node"), type, x: Math.max(20, p.x - size.w / 2), y: Math.max(20, p.y - size.h / 2), ...size, label: d.label, note: d.note, marker: "待讨论" }; commit(() => activeCanvas().nodes.push(node), "节点已添加"); selectedNodeId = node.id; render(); if (type === "text") beginEdit(node.id); }
function addEdge(from, to) { if (!from || !to || from === to) return; const canvas = activeCanvas(); if (canvas.edges.some((e) => e.from === from && e.to === to)) return showToast("这两个节点已经连接"); commit(() => canvas.edges.push({ id: createId("edge"), from, to }), "连线已添加"); selectedNodeId = to; selectedEdgeId = null; }
function deleteSelection() { if (!selectedNodeId && !selectedEdgeId) return; commit(() => { const c = activeCanvas(); if (selectedNodeId) { c.nodes = c.nodes.filter((n) => n.id !== selectedNodeId); c.edges = c.edges.filter((e) => e.from !== selectedNodeId && e.to !== selectedNodeId); } else c.edges = c.edges.filter((e) => e.id !== selectedEdgeId); selectedNodeId = null; selectedEdgeId = null; }, "已删除"); }
function beginEdit(id) { const node = activeCanvas().nodes.find((n) => n.id === id), el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(id)}"] .node-label`); if (!node || !el) return; history.push(snapshot()); future = []; editing = { nodeId: id }; el.contentEditable = "true"; el.focus(); const range = document.createRange(); range.selectNodeContents(el); range.collapse(false); const sel = window.getSelection(); sel?.removeAllRanges(); sel?.addRange(range); }
function finishEdit(el) { if (!editing) return; const node = activeCanvas().nodes.find((n) => n.id === editing.nodeId); if (node) node.label = el.textContent.trim() || "未命名节点"; el.contentEditable = "false"; editing = null; render(); saveLocal("文字已保存"); }
function undo() { if (!history.length) return showToast("没有可撤销的操作"); future.push(snapshot()); state = normalizeState(history.pop()); selectedNodeId = null; resizeModeNodeId = null; selectedEdgeId = null; render(); saveLocal("已撤销"); }
function redo() { if (!future.length) return showToast("没有可重做的操作"); history.push(snapshot()); state = normalizeState(future.pop()); selectedNodeId = null; resizeModeNodeId = null; selectedEdgeId = null; render(); saveLocal("已重做"); }
function changeZoom(next, cx = viewport.clientWidth / 2, cy = viewport.clientHeight / 2) { const c = activeCanvas(), v = c.view || { zoom: 1, panX: 0, panY: 0 }, before = { x: (cx - v.panX) / v.zoom, y: (cy - v.panY) / v.zoom }; v.zoom = clampZoom(next); v.panX = cx - before.x * v.zoom; v.panY = cy - before.y * v.zoom; c.view = v; renderTransform(); markDirty(); }
function stepZoom(direction) { const v = activeCanvas().view || { zoom: 1 }, isBelowFineThreshold = v.zoom < ZOOM_FINE_THRESHOLD - 1e-9; const delta = direction === "in" ? ZOOM_CLICK_IN : isBelowFineThreshold ? -ZOOM_CLICK_OUT_FINE : -ZOOM_CLICK_OUT_COARSE; changeZoom(v.zoom + delta); }
function exportWorkflow() { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = `${activeCanvas().name || "工作流"}.json`; link.click(); URL.revokeObjectURL(url); showToast("工作流 JSON 已导出"); }
function createCanvas() { const name = window.prompt("请输入新画布名称", `工作流 ${state.canvases.length + 1}`); if (!name?.trim()) return; commit(() => { const c = { id: createId("canvas"), name: name.trim(), nodes: [], edges: [], view: { zoom: 1, panX: 0, panY: 0 } }; state.canvases.push(c); state.activeCanvasId = c.id; selectedNodeId = null; selectedEdgeId = null; }, "新画布已创建"); }
function closeCanvas(id) { if (state.canvases.length === 1) return showToast("至少保留一个画布"); const c = state.canvases.find((x) => x.id === id); if (!c || !window.confirm(`关闭“${c.name}”？未导出的改动仍保留在本机保存中。`)) return; commit(() => { state.canvases = state.canvases.filter((x) => x.id !== id); if (state.activeCanvasId === id) state.activeCanvasId = state.canvases[0].id; }, "画布已关闭"); }
function renameCanvas(id) { const c = state.canvases.find((x) => x.id === id), name = c && window.prompt("请输入画布名称", c.name); if (!c || !name?.trim() || name.trim() === c.name) return; commit(() => { c.name = name.trim(); }, "画布名称已更新"); }
function portPoint(n, side) { if (side === "top") return { x: n.x + n.w / 2, y: n.y }; if (side === "right") return { x: n.x + n.w, y: n.y + n.h / 2 }; if (side === "bottom") return { x: n.x + n.w / 2, y: n.y + n.h }; return { x: n.x, y: n.y + n.h / 2 }; }
function updateTemporaryEdge(x, y) { if (!connecting) return; const n = activeCanvas().nodes.find((item) => item.id === connecting.sourceId); if (!n) return; const start = portPoint(n, connecting.side), p = screenToWorld(x, y); temporaryEdge.hidden = false; temporaryEdge.setAttribute("d", curvePath(start.x, start.y, p.x, p.y)); }
function finishConnection(e) { if (!connecting) return; const target = document.elementFromPoint(e.clientX, e.clientY)?.closest?.(".node"), targetId = target?.dataset.nodeId; temporaryEdge.hidden = true; if (targetId && targetId !== connecting.sourceId) addEdge(connecting.sourceId, targetId); connecting = null; render(); }
function beginResize(e, nodeId, handle) { if (activeTool !== "select") return; const node = activeCanvas().nodes.find((item) => item.id === nodeId); if (!node) return; e.preventDefault(); e.stopPropagation(); history.push(snapshot()); if (history.length > 80) history.shift(); future = []; resizing = { nodeId, handle, pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, originX: node.x, originY: node.y, originW: node.w, originH: node.h, changed: false }; viewport.setPointerCapture?.(e.pointerId); }
function updateResize(e) { if (!resizing) return; const node = activeCanvas().nodes.find((item) => item.id === resizing.nodeId), view = activeCanvas().view || { zoom: 1 }; if (!node) return; const dx = (e.clientX - resizing.startX) / view.zoom, dy = (e.clientY - resizing.startY) / view.zoom, handle = resizing.handle, minimum = minSizeForType(node.type), right = resizing.originX + resizing.originW, bottom = resizing.originY + resizing.originH; let x = resizing.originX, y = resizing.originY, w = resizing.originW, h = resizing.originH; if (handle.includes("e")) w = resizing.originW + dx; if (handle.includes("s")) h = resizing.originH + dy; if (handle.includes("w")) { w = resizing.originW - dx; x = resizing.originX + dx; } if (handle.includes("n")) { h = resizing.originH - dy; y = resizing.originY + dy; } if (w < minimum.w) { w = minimum.w; if (handle.includes("w")) x = right - w; } if (h < minimum.h) { h = minimum.h; if (handle.includes("n")) y = bottom - h; } node.x = Math.max(10, Math.round(x)); node.y = Math.max(10, Math.round(y)); node.w = Math.round(w); node.h = Math.round(h); resizing.changed = resizing.changed || Math.abs(dx) > 2 || Math.abs(dy) > 2; renderNodes(); renderEdges(); markDirty(); }
function finishResize() { if (!resizing) return; if (!resizing.changed) history.pop(); else saveLocal("节点大小已保存"); resizing = null; render(); }
function cancelResize() { if (!resizing) return; const node = activeCanvas().nodes.find((item) => item.id === resizing.nodeId); if (node) { node.x = resizing.originX; node.y = resizing.originY; node.w = resizing.originW; node.h = resizing.originH; } history.pop(); resizing = null; render(); }
function beginInspectorEdit(field) { if (inspectorEdit?.field === field) return; history.push(snapshot()); if (history.length > 80) history.shift(); future = []; inspectorEdit = { field, nodeId: selectedNodeId }; }
function updateInspectorField(field, value) { const node = activeCanvas().nodes.find((item) => item.id === selectedNodeId); if (!node || !["label", "note", "marker"].includes(field)) return; node[field] = value; renderNodes(); updateStatus(); markDirty(); }
function finishInspectorEdit() { if (!inspectorEdit) return; const node = activeCanvas().nodes.find((item) => item.id === inspectorEdit.nodeId); if (node) { node.label = node.label.trim() || "未命名节点"; node.note = node.note.trim(); node.marker = DISCUSSION_MARKERS.includes(node.marker) ? node.marker : "待讨论"; } inspectorEdit = null; render(); saveLocal("节点信息已保存"); }

document.querySelectorAll(".tool-button").forEach((b) => b.addEventListener("click", () => setTool(b.dataset.tool)));
document.querySelector(".topbar-groups").addEventListener("click", (e) => { const a = e.target.closest("[data-action]")?.dataset.action; if (a === "undo") undo(); if (a === "redo") redo(); if (a === "export") exportWorkflow(); if (a === "save") { saveLocal(); showToast("已保存到本机"); } });
document.querySelector(".statusbar").addEventListener("click", (e) => { const a = e.target.closest("[data-action]")?.dataset.action; if (a === "zoom-out") stepZoom("out"); if (a === "zoom-in") stepZoom("in"); if (a === "zoom-reset") changeZoom(1); });
canvasTabs.addEventListener("click", (e) => { const add = e.target.closest('[data-action="new-canvas"]'), close = e.target.closest(".tab-close"), tab = e.target.closest(".canvas-tab"); if (add) return createCanvas(); if (!tab) return; if (close) return closeCanvas(tab.dataset.canvasId); if (state.activeCanvasId === tab.dataset.canvasId) return; state.activeCanvasId = tab.dataset.canvasId; selectedNodeId = null; resizeModeNodeId = null; selectedEdgeId = null; connectorSourceId = null; render(); markDirty(); });
canvasTabs.addEventListener("dblclick", (e) => { const tab = e.target.closest(".canvas-tab"); if (tab && !e.target.closest(".tab-close")) renameCanvas(tab.dataset.canvasId); });
inspector.addEventListener("focusin", (e) => { const field = e.target.closest("[name]")?.name; if (field) beginInspectorEdit(field); });
inspector.addEventListener("input", (e) => { const field = e.target.closest("[name]")?.name; if (field) updateInspectorField(field, e.target.value); });
inspector.addEventListener("change", (e) => { if (!e.target.matches("[name]")) return; updateInspectorField(e.target.name, e.target.value); finishInspectorEdit(); });
inspector.addEventListener("focusout", (e) => { if (e.target.matches("[name]")) window.setTimeout(() => { if (!inspector.contains(document.activeElement)) finishInspectorEdit(); }, 0); });
inspector.addEventListener("click", (e) => { const target = e.target.closest("[data-inspect-node-id]"); if (!target) return; selectedNodeId = target.dataset.inspectNodeId; selectedEdgeId = null; connectorSourceId = null; render(); });
importInput.addEventListener("change", async () => { const file = importInput.files?.[0]; if (!file) return; try { history.push(snapshot()); future = []; state = normalizeState(JSON.parse(await file.text())); selectedNodeId = null; selectedEdgeId = null; render(); saveLocal("已导入工作流"); showToast("工作流已导入"); } catch { showToast("导入失败：文件不是有效的工作流 JSON"); } finally { importInput.value = ""; } });

nodeLayer.addEventListener("click", (e) => { const resizeToggle = e.target.closest(".resize-toggle"); if (!resizeToggle) return; e.preventDefault(); e.stopPropagation(); if (activeTool !== "select") setTool("select"); resizeModeNodeId = resizeModeNodeId === resizeToggle.dataset.nodeId ? null : resizeToggle.dataset.nodeId; renderNodes(); updateStatus(); });
nodeLayer.addEventListener("pointerdown", (e) => { const resizeToggle = e.target.closest(".resize-toggle"); if (resizeToggle) { e.preventDefault(); e.stopPropagation(); return; } const resizeHandle = e.target.closest(".resize-handle"); if (resizeHandle) return beginResize(e, resizeHandle.dataset.nodeId, resizeHandle.dataset.handle); const port = e.target.closest(".port"), el = e.target.closest(".node"); if (!el) return; const id = el.dataset.nodeId; if (port) { e.preventDefault(); e.stopPropagation(); resizeModeNodeId = null; connecting = { sourceId: id, side: port.dataset.side, pointerId: e.pointerId }; connectorSourceId = id; viewport.setPointerCapture?.(e.pointerId); updateTemporaryEdge(e.clientX, e.clientY); renderNodes(); return; } if (activeTool === "connector") { e.preventDefault(); if (!connectorSourceId) { connectorSourceId = id; selectedNodeId = id; resizeModeNodeId = null; selectedEdgeId = null; render(); } else { addEdge(connectorSourceId, id); connectorSourceId = null; render(); } return; } if (activeTool !== "select") return; e.preventDefault(); selectedNodeId = id; resizeModeNodeId = null; selectedEdgeId = null; const n = activeCanvas().nodes.find((x) => x.id === id); drag = { nodeId: id, pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, originX: n.x, originY: n.y, changed: false }; history.push(snapshot()); future = []; viewport.setPointerCapture?.(e.pointerId); renderNodes(); renderInspector(); updateStatus(); });
nodeLayer.addEventListener("dblclick", (e) => { const label = e.target.closest(".node-label"), el = e.target.closest(".node"); if (label && el) { e.preventDefault(); e.stopPropagation(); beginEdit(el.dataset.nodeId); } });
nodeLayer.addEventListener("focusout", (e) => { if (e.target.matches(".node-label[contenteditable='true']")) finishEdit(e.target); });
edgeGroup.addEventListener("click", (e) => { const edge = e.target.closest(".edge"); if (!edge) return; selectedEdgeId = edge.dataset.edgeId; selectedNodeId = null; renderEdges(); renderInspector(); updateStatus(); });
viewport.addEventListener("pointerdown", (e) => { if (connecting) return; if (e.target.closest?.(".node") || e.target.closest?.("button")) return; if (activeTool !== "select" && activeTool !== "connector") { if (e.button === 0) addNode(activeTool, e.clientX, e.clientY); return; } if (e.button !== 0 && e.button !== 1) return; e.preventDefault(); const v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; pan = { pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, originX: v.panX, originY: v.panY }; viewport.classList.add("is-panning"); viewport.setPointerCapture?.(e.pointerId); });
viewport.addEventListener("pointermove", (e) => { if (connecting) return updateTemporaryEdge(e.clientX, e.clientY); if (resizing) return updateResize(e); if (drag) { const n = activeCanvas().nodes.find((x) => x.id === drag.nodeId), v = activeCanvas().view || { zoom: 1 }; if (!n) return; n.x = Math.max(10, drag.originX + (e.clientX - drag.startX) / v.zoom); n.y = Math.max(10, drag.originY + (e.clientY - drag.startY) / v.zoom); drag.changed = drag.changed || Math.abs(e.clientX - drag.startX) > 2 || Math.abs(e.clientY - drag.startY) > 2; renderNodes(); renderEdges(); markDirty(); } if (pan) { const v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; v.panX = pan.originX + e.clientX - pan.startX; v.panY = pan.originY + e.clientY - pan.startY; activeCanvas().view = v; renderTransform(); markDirty(); } });
viewport.addEventListener("pointerup", (e) => { if (connecting) return finishConnection(e); if (resizing) return finishResize(); if (drag) { if (!drag.changed) history.pop(); else saveLocal("节点位置已保存"); drag = null; render(); } if (pan) { pan = null; viewport.classList.remove("is-panning"); saveLocal("画布位置已保存"); } });
viewport.addEventListener("pointercancel", () => { drag = null; cancelResize(); pan = null; connecting = null; temporaryEdge.hidden = true; viewport.classList.remove("is-panning"); render(); });
viewport.addEventListener("wheel", (e) => { e.preventDefault(); const v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; if (e.ctrlKey || e.metaKey) changeZoom(v.zoom + (e.deltaY > 0 ? -.08 : .08), e.clientX - viewport.getBoundingClientRect().left, e.clientY - viewport.getBoundingClientRect().top); else { v.panX -= e.deltaX; v.panY -= e.deltaY; activeCanvas().view = v; renderTransform(); markDirty(); } }, { passive: false });
viewport.addEventListener("dblclick", (e) => { if (!e.target.closest?.(".node, .port") && activeTool === "text") addNode("text", e.clientX, e.clientY); });
document.addEventListener("keydown", (e) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z") { e.preventDefault(); undo(); return; } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "y") { e.preventDefault(); redo(); return; } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "s") { e.preventDefault(); saveLocal(); showToast("已保存到本机"); return; } if (editing) { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); e.target.blur(); } return; } if (e.key === "Delete" || e.key === "Backspace") deleteSelection(); if (e.key.toLowerCase() === "v") setTool("select"); if (e.key.toLowerCase() === "t") setTool("text"); });
window.addEventListener("pagehide", flushPendingSave);
window.addEventListener("beforeunload", flushPendingSave);
render(); saveStatus.textContent = hasSavedDraft() ? "已从本机恢复" : "尚未保存";
