const STORAGE_KEY = "workflow-canvas-communication-draft-v1";
const LEGACY_STORAGE_KEY = "workflow-canvas-legal-blueprint-v1";
const MODULE_STORAGE_KEY = "workflow-canvas-module-library-v1";
const ZOOM_MIN = 0.01;
const ZOOM_MAX = 2.2;
const ZOOM_CLICK_IN = 0.05;
const ZOOM_CLICK_OUT_COARSE = 0.05;
const ZOOM_CLICK_OUT_FINE = 0.01;
const ZOOM_FINE_THRESHOLD = 0.1;
const AUTOSAVE_DELAY_MS = 600;
const DISCUSSION_MARKERS = ["待讨论", "已决定", "有疑问", "不采用"];
const NODE_DEFAULTS = {
  rect: { label: "步骤", note: "双击编辑文字" }, diamond: { label: "判断", note: "条件分支" }, circle: { label: "开始 / 结束", note: "" }, document: { label: "材料", note: "来源或文档" }, triangle: { label: "提醒", note: "需要处理" }, text: { label: "输入文字", note: "" },
};
const NODE_TYPE_LABELS = { rect: "步骤（矩形）", diamond: "判断（菱形）", circle: "开始 / 结束（圆形）", document: "材料（文档形）", triangle: "提醒（三角形）", text: "文字" };
const RESIZE_HANDLES_BY_TYPE = {
  rect: ["nw", "ne", "se", "sw"],
  document: ["nw", "ne", "se", "sw"],
  text: ["nw", "ne", "se", "sw"],
  diamond: ["n", "e", "s", "w"],
  circle: ["n", "e", "s", "w"],
  triangle: ["n", "se", "sw"],
};
const NODE_MIN_SIZES = { rect: { w: 120, h: 92 }, document: { w: 120, h: 92 }, diamond: { w: 76, h: 76 }, circle: { w: 76, h: 76 }, triangle: { w: 96, h: 84 }, text: { w: 80, h: 40 } };
const viewport = document.querySelector("#viewport"), surface = document.querySelector("#surface"), nodeLayer = document.querySelector("#nodeLayer"), edgeGroup = document.querySelector("#edges"), temporaryEdge = document.querySelector("#temporaryEdge"), canvasTabs = document.querySelector("#canvasTabs"), importInput = document.querySelector("#importInput"), saveStatus = document.querySelector("#saveStatus"), selectionStatus = document.querySelector("#selectionStatus"), statusDot = document.querySelector("#statusDot"), zoomValue = document.querySelector("#zoomValue"), selectionHint = document.querySelector("#selectionHint"), toast = document.querySelector("#toast"), inspector = document.querySelector("#nodeInspector"), inspectorEmpty = document.querySelector("#inspectorEmpty"), inspectorForm = document.querySelector("#inspectorForm"), inspectorCount = document.querySelector("#inspectorCount"), inspectorName = document.querySelector("#inspectorName"), inspectorNote = document.querySelector("#inspectorNote"), inspectorType = document.querySelector("#inspectorType"), inspectorMarker = document.querySelector("#inspectorMarker"), previousNodes = document.querySelector("#previousNodes"), nextNodes = document.querySelector("#nextNodes"), previousCount = document.querySelector("#previousCount"), nextCount = document.querySelector("#nextCount"), marquee = document.querySelector("#marquee"), multiSelectPanel = document.querySelector("#multiSelectPanel"), multiSelectSummary = document.querySelector("#multiSelectSummary"), moduleModal = document.querySelector("#moduleModal"), moduleList = document.querySelector("#moduleList"), moduleEditBar = document.querySelector("#moduleEditBar"), moduleEditName = document.querySelector("#moduleEditName");
let state = loadState(), activeTool = "select", selectedNodeId = null, resizeModeNodeId = null, selectedEdgeId = null, connectorSourceId = null, historyByCanvas = new Map(), drag = null, resizing = null, pan = null, connecting = null, editing = null, inspectorEdit = null, toastTimer, autosaveTimer = null, isDirty = false, selectedNodeIds = new Set(), marqueeDrag = null, moduleLibrary = loadModules(), modulePlaceOffset = 0, lastModalTrigger = null, lastLabelClick = null, moduleEditing = null;

function createId(prefix) { return `${prefix}-${globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`}`; }
function defaultState() { return { version: 1, activeCanvasId: "canvas-main", canvases: [{ id: "canvas-main", name: "产品逻辑草图", nodes: [{ id: "node-source", type: "document", x: 50, y: 300, w: 176, h: 92, label: "收集材料", note: "把已有信息放到一起", marker: "已决定" }, { id: "node-analysis", type: "diamond", x: 280, y: 282, w: 112, h: 112, label: "形成判断", note: "这里需要讨论依据", marker: "待讨论" }, { id: "node-review", type: "rect", x: 470, y: 300, w: 176, h: 92, label: "共同核对", note: "人与 AI 一起检查", marker: "有疑问" }, { id: "node-publish", type: "document", x: 680, y: 300, w: 176, h: 92, label: "整理结论", note: "形成下一步沟通材料", marker: "待讨论" }], edges: [{ id: "edge-1", from: "node-source", to: "node-analysis" }, { id: "edge-2", from: "node-analysis", to: "node-review" }, { id: "edge-3", from: "node-review", to: "node-publish" }], view: { zoom: 1, panX: 0, panY: 0 } }] }; }
function clampZoom(value) { return Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, Number.isFinite(value) ? value : 1)); }
function minSizeForType(type) { return NODE_MIN_SIZES[type] || NODE_MIN_SIZES.rect; }
function normalizeNode(node) { if (!node || typeof node.id !== "string") return null; const type = NODE_DEFAULTS[node.type] ? node.type : "rect", d = NODE_DEFAULTS[type], minimum = minSizeForType(type), fallbackW = type === "diamond" || type === "circle" ? 112 : type === "text" ? 150 : type === "triangle" ? 126 : 176, fallbackH = type === "diamond" || type === "circle" ? 112 : type === "text" ? 48 : type === "triangle" ? 112 : 92, marker = typeof node.marker === "string" && DISCUSSION_MARKERS.includes(node.marker.trim()) ? node.marker.trim() : "待讨论"; return { id: node.id, type, x: Number.isFinite(node.x) ? node.x : 240, y: Number.isFinite(node.y) ? node.y : 240, w: Math.max(minimum.w, Number.isFinite(node.w) ? node.w : fallbackW), h: Math.max(minimum.h, Number.isFinite(node.h) ? node.h : fallbackH), label: typeof node.label === "string" ? node.label.trim() || "未命名节点" : d.label, note: typeof node.note === "string" ? node.note.trim() : d.note, marker }; }
function normalizeState(input) { if (!input || !Array.isArray(input.canvases) || !input.canvases.length) return defaultState(); const seenIds = new Set(); const canvases = input.canvases.map((canvas, i) => { let id = typeof canvas.id === "string" ? canvas.id : createId("canvas"); if (seenIds.has(id)) id = createId("canvas"); seenIds.add(id); const nodeIds = new Set(); const nodes = Array.isArray(canvas.nodes) ? (() => { const seen = new Set(); return canvas.nodes.map(normalizeNode).filter(Boolean).map((n) => { if (seen.has(n.id)) n.id = createId("node"); seen.add(n.id); nodeIds.add(n.id); return n; }); })() : []; const edges = Array.isArray(canvas.edges) ? canvas.edges.filter((e) => e && typeof e.from === "string" && typeof e.to === "string" && nodeIds.has(e.from) && nodeIds.has(e.to) && e.from !== e.to).map((e) => ({ id: typeof e.id === "string" ? e.id : createId("edge"), from: e.from, to: e.to })) : []; return { id, name: typeof canvas.name === "string" && canvas.name.trim() ? canvas.name.trim() : `工作流 ${i + 1}`, nodes, edges, view: { zoom: clampZoom(canvas.view?.zoom), panX: Number.isFinite(canvas.view?.panX) ? canvas.view.panX : 0, panY: Number.isFinite(canvas.view?.panY) ? canvas.view.panY : 0 } }; }); return { version: 1, activeCanvasId: canvases.some((c) => c.id === input.activeCanvasId) ? input.activeCanvasId : canvases[0].id, canvases }; }
function loadState() { try { const current = localStorage.getItem(STORAGE_KEY), legacy = current ? null : localStorage.getItem(LEGACY_STORAGE_KEY), saved = current || legacy; if (!saved) return defaultState(); const normalized = normalizeState(JSON.parse(saved)); if (legacy) { localStorage.setItem(STORAGE_KEY, JSON.stringify(normalized)); localStorage.removeItem(LEGACY_STORAGE_KEY); } return normalized; } catch { return defaultState(); } }
function hasSavedDraft() { try { return Boolean(localStorage.getItem(STORAGE_KEY) || localStorage.getItem(LEGACY_STORAGE_KEY)); } catch { return false; } }
function activeCanvas() { return state.canvases.find((c) => c.id === state.activeCanvasId) || state.canvases[0]; }
function canvasStack(canvasId) { let stack = historyByCanvas.get(canvasId); if (!stack) { stack = { history: [], future: [] }; historyByCanvas.set(canvasId, stack); } return stack; }
function canvasSnapshot(canvas) { return { nodes: JSON.parse(JSON.stringify(canvas.nodes)), edges: JSON.parse(JSON.stringify(canvas.edges)) }; }
function pushHistory() { const c = activeCanvas(); const stack = canvasStack(c.id); stack.history.push(canvasSnapshot(c)); if (stack.history.length > 80) stack.history.shift(); stack.future = []; }
function clamp(value, lo, hi) { return Math.max(lo, Math.min(hi, value)); }
function focusInEditableControl() { const el = document.activeElement; if (!el) return false; if (el.isContentEditable) return true; const tag = el.tagName; if (tag === "INPUT") return !el.readOnly && !["checkbox", "radio", "button", "submit", "reset", "file"].includes(el.type); return tag === "TEXTAREA" || tag === "SELECT"; }
function commitPendingEdit() { if (!editing) return; const node = activeCanvas().nodes.find((n) => n.id === editing.nodeId); const el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(editing.nodeId)}"] .node-label`); const value = el ? el.textContent.trim() || "未命名节点" : editing.before; const changed = !!node && value !== editing.before; if (node) node.label = value; if (el) el.contentEditable = "false"; if (!changed) canvasStack(activeCanvas().id).history.length = editing.histLen; editing = null; if (changed) markDirty(); }
function render() { renderTabs(); renderNodes(); renderEdges(); renderTransform(); renderInspector(); renderModuleEditBar(); updateStatus(); }
function renderModuleEditBar() { moduleEditBar.hidden = !moduleEditing; moduleEditName.textContent = moduleEditing ? moduleEditing.name : ""; viewport.classList.toggle("is-module-editing", !!moduleEditing); }
function renderTabs() { canvasTabs.innerHTML = ""; state.canvases.forEach((canvas) => { const tab = document.createElement("div"); tab.className = `canvas-tab${canvas.id === state.activeCanvasId ? " is-active" : ""}`; tab.dataset.canvasId = canvas.id; tab.innerHTML = `<span class="tab-label"></span><button class="tab-close" title="关闭画布" aria-label="关闭画布">×</button>`; tab.querySelector(".tab-label").textContent = canvas.name; canvasTabs.append(tab); }); const add = document.createElement("button"); add.className = "new-tab"; add.dataset.action = "new-canvas"; add.title = "新建画布"; add.textContent = "+"; canvasTabs.append(add); }
function markerClass(marker) { return `marker-${DISCUSSION_MARKERS.indexOf(marker) >= 0 ? DISCUSSION_MARKERS.indexOf(marker) : 0}`; }
function resizeHandlesForNode(node) { return RESIZE_HANDLES_BY_TYPE[node.type] || RESIZE_HANDLES_BY_TYPE.rect; }
function resizeHandlePositions(node) { return { nw: [node.x - 5, node.y - 5], n: [node.x + node.w / 2 - 5, node.y - 19], ne: [node.x + node.w - 5, node.y - 5], e: [node.x + node.w + 9, node.y + node.h / 2 - 5], se: [node.x + node.w - 5, node.y + node.h - 5], s: [node.x + node.w / 2 - 5, node.y + node.h + 9], sw: [node.x - 5, node.y + node.h - 5], w: [node.x - 19, node.y + node.h / 2 - 5] }; }
function renderResizeHandles(node) { if (!node || activeTool !== "select" || resizeModeNodeId !== node.id) return; const positions = resizeHandlePositions(node); resizeHandlesForNode(node).forEach((handle) => { const el = document.createElement("div"); el.className = `resize-handle resize-${handle}`; el.dataset.nodeId = node.id; el.dataset.handle = handle; el.title = "调整节点大小"; el.style.left = `${positions[handle][0]}px`; el.style.top = `${positions[handle][1]}px`; nodeLayer.append(el); }); }
function renderNodes() { commitPendingEdit(); nodeLayer.innerHTML = ""; const canvas = activeCanvas(); canvas.nodes.forEach((node) => { const minimum = minSizeForType(node.type), isSelected = selectedNodeId === node.id, isInSelection = selectedNodeIds.has(node.id), isResizeMode = resizeModeNodeId === node.id, el = document.createElement("div"); el.className = `node shape-${node.type}${isSelected ? " is-selected" : ""}${isInSelection ? " is-in-selection" : ""}${connectorSourceId === node.id ? " is-connecting" : ""}`; el.dataset.nodeId = node.id; el.style.left = `${node.x}px`; el.style.top = `${node.y}px`; el.style.width = `${Math.max(node.w, minimum.w)}px`; el.style.minHeight = `${Math.max(node.h, minimum.h)}px`; el.innerHTML = `<div class="node-content"><span class="node-label"></span><span class="node-note"></span><span class="node-marker"></span></div><button class="resize-toggle${isResizeMode ? " is-active" : ""}" type="button" title="${isResizeMode ? "隐藏尺寸控制点" : "显示尺寸控制点"}" aria-label="${isResizeMode ? "隐藏尺寸控制点" : "显示尺寸控制点"}" aria-pressed="${isResizeMode}"><span aria-hidden="true">⤢</span></button><span class="port" data-side="top" title="从上方连接"></span><span class="port" data-side="right" title="从右侧连接"></span><span class="port" data-side="bottom" title="从下方连接"></span><span class="port" data-side="left" title="从左侧连接"></span>`; el.querySelector(".node-label").textContent = node.label; el.querySelector(".node-note").textContent = node.note; el.querySelector(".node-marker").textContent = node.marker; el.querySelector(".node-marker").classList.add(markerClass(node.marker)); if (!node.note) el.querySelector(".node-note").hidden = true; el.querySelector(".resize-toggle").dataset.nodeId = node.id; el.querySelector(".resize-toggle").hidden = !isSelected; nodeLayer.append(el); }); renderResizeHandles(canvas.nodes.find((node) => node.id === selectedNodeId)); document.querySelector("#canvasEmpty").hidden = canvas.nodes.length > 0; }
function relationNodes(nodeId, direction) { const canvas = activeCanvas(), ids = canvas.edges.filter((edge) => direction === "previous" ? edge.to === nodeId : edge.from === nodeId).map((edge) => direction === "previous" ? edge.from : edge.to); return ids.map((id) => canvas.nodes.find((node) => node.id === id)).filter(Boolean); }
function renderRelationList(container, nodes, emptyText) { container.innerHTML = ""; if (!nodes.length) { const empty = document.createElement("span"); empty.className = "relation-empty"; empty.textContent = emptyText; container.append(empty); return; } nodes.forEach((node) => { const button = document.createElement("button"); button.type = "button"; button.className = "relation-item"; button.dataset.inspectNodeId = node.id; button.title = `选择${node.label}`; button.textContent = node.label; container.append(button); }); }
function renderInspector() { const node = activeCanvas().nodes.find((item) => item.id === selectedNodeId); const multi = selectedNodeIds.size > 0; inspectorEmpty.hidden = Boolean(node) || multi; inspectorForm.hidden = !node || multi; multiSelectPanel.hidden = !multi; inspectorCount.textContent = multi ? `${selectedNodeIds.size} 个节点` : node ? "1 个节点" : "未选择"; if (multi) { const canvas = activeCanvas(); const internal = canvas.edges.filter((e) => selectedNodeIds.has(e.from) && selectedNodeIds.has(e.to)).length; multiSelectSummary.textContent = `已框选 ${selectedNodeIds.size} 个节点、${internal} 条内部连线。可封装为模块，以后在任意画布复用。`; return; } if (!node) { inspectorName.value = ""; inspectorNote.value = ""; inspectorType.value = ""; inspectorMarker.value = "待讨论"; previousCount.textContent = "0"; nextCount.textContent = "0"; previousNodes.innerHTML = ""; nextNodes.innerHTML = ""; return; } inspectorName.value = node.label; inspectorNote.value = node.note; inspectorType.value = NODE_TYPE_LABELS[node.type] || node.type; inspectorMarker.value = DISCUSSION_MARKERS.includes(node.marker) ? node.marker : "待讨论"; const previous = relationNodes(node.id, "previous"), next = relationNodes(node.id, "next"); previousCount.textContent = String(previous.length); nextCount.textContent = String(next.length); renderRelationList(previousNodes, previous, "无前置节点"); renderRelationList(nextNodes, next, "无后续节点"); }
function anchorBetween(node, other) { const cx = node.x + node.w / 2, cy = node.y + node.h / 2, dx = other.x + other.w / 2 - cx, dy = other.y + other.h / 2 - cy; if (Math.abs(dx) > Math.abs(dy)) return { x: dx >= 0 ? node.x + node.w : node.x, y: cy }; return { x: cx, y: dy >= 0 ? node.y + node.h : node.y }; }
function curvePath(x1, y1, x2, y2) { const bend = Math.max(50, Math.abs(x2 - x1) * .38), direction = x2 >= x1 ? 1 : -1; return `M ${x1} ${y1} C ${x1 + bend * direction} ${y1}, ${x2 - bend * direction} ${y2}, ${x2} ${y2}`; }
function renderEdges() { edgeGroup.innerHTML = ""; const canvas = activeCanvas(); canvas.edges.forEach((edge) => { const from = canvas.nodes.find((n) => n.id === edge.from), to = canvas.nodes.find((n) => n.id === edge.to); if (!from || !to) return; const a = anchorBetween(from, to), b = anchorBetween(to, from), path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.classList.add("edge"); if (selectedEdgeId === edge.id) path.classList.add("is-selected"); if (selectedNodeIds.has(edge.from) && selectedNodeIds.has(edge.to)) path.classList.add("is-in-selection"); path.dataset.edgeId = edge.id; path.setAttribute("d", curvePath(a.x, a.y, b.x, b.y)); edgeGroup.append(path); }); }
function renderTransform() { const view = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; clampPan(view); surface.style.transform = `translate(${view.panX}px, ${view.panY}px) scale(${view.zoom})`; zoomValue.textContent = `${Math.round(view.zoom * 100)}%`; }
function updateStatus() { if (selectedNodeIds.size > 0) { selectionStatus.textContent = `已框选 ${selectedNodeIds.size} 个节点`; selectionHint.hidden = true; return; } const node = activeCanvas().nodes.find((n) => n.id === selectedNodeId); selectionStatus.textContent = node ? `已选择：${node.label}` : selectedEdgeId ? "已选择：连线" : "未选择节点"; selectionHint.hidden = !node; if (node) selectionHint.textContent = `${node.label} · 点击右上角缩放图标，再拖动控制点调整大小；拖动圆点连接`; }
function commit(mutator, message = "已更新") { pushHistory(); mutator(); render(); saveLocal(message); }
function applyNoHistory(mutator, message = "已更新") { mutator(); render(); saveLocal(message); }
function saveLocal(message = "已保存到本机") { clearTimeout(autosaveTimer); autosaveTimer = null; try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); saveStatus.textContent = message; statusDot.classList.remove("is-dirty"); isDirty = false; return true; } catch { saveStatus.textContent = message === "已自动保存" ? "自动保存失败" : "保存失败"; statusDot.classList.add("is-dirty"); isDirty = true; return false; } }
function markDirty() { isDirty = true; saveStatus.textContent = "有未保存改动"; statusDot.classList.add("is-dirty"); clearTimeout(autosaveTimer); autosaveTimer = setTimeout(() => { autosaveTimer = null; saveLocal("已自动保存"); }, AUTOSAVE_DELAY_MS); }
function flushPendingSave() { if (editing) commitPendingEdit(); if (inspectorEdit) finishInspectorEdit(); if (isDirty || autosaveTimer) saveLocal("已保存到本机"); }
function showToast(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add("is-visible"); toastTimer = setTimeout(() => toast.classList.remove("is-visible"), 1900); }
function setTool(tool) { activeTool = tool; connectorSourceId = null; document.querySelectorAll(".tool-button").forEach((b) => b.classList.toggle("is-active", b.dataset.tool === tool)); showToast(tool === "select" ? "选择工具" : tool === "connector" ? "连接工具：点击两个节点或拖动端点" : tool === "marquee" ? "框选工具：在空白处拖动框选多个节点" : "在画布空白处放置节点"); }
function screenToWorld(x, y) { const r = viewport.getBoundingClientRect(), view = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; return { x: (x - r.left - view.panX) / view.zoom, y: (y - r.top - view.panY) / view.zoom }; }
function addNode(type, x, y) { const p = screenToWorld(x, y), d = NODE_DEFAULTS[type], size = type === "diamond" || type === "circle" ? { w: 112, h: 112 } : type === "text" ? { w: 150, h: 48 } : type === "triangle" ? { w: 126, h: 112 } : { w: 176, h: 92 }, node = { id: createId("node"), type, x: clamp(Math.round(p.x - size.w / 2), 10, Math.max(10, 2400 - size.w)), y: clamp(Math.round(p.y - size.h / 2), 10, Math.max(10, 1500 - size.h)), ...size, label: d.label, note: d.note, marker: "待讨论" }; commit(() => { activeCanvas().nodes.push(node); selectedNodeId = node.id; selectedNodeIds = new Set(); }, "节点已添加"); if (moduleEditing) moduleEditing.nodeIds.add(node.id); if (type === "text") beginEdit(node.id); }
function addEdge(from, to) { if (!from || !to || from === to) return; const canvas = activeCanvas(); if (canvas.edges.some((e) => (e.from === from && e.to === to) || (e.from === to && e.to === from))) return showToast("这两个节点之间已有连线（不支持同一对节点连两条）"); commit(() => canvas.edges.push({ id: createId("edge"), from, to }), "连线已添加"); selectedNodeId = to; selectedEdgeId = null; selectedNodeIds = new Set(); }
function deleteSelection() { if (!selectedNodeId && !selectedEdgeId && !selectedNodeIds.size) return; connecting = null; temporaryEdge.hidden = true; connectorSourceId = null; resizeModeNodeId = null; commit(() => { const c = activeCanvas(); if (selectedNodeIds.size) { const ids = new Set(selectedNodeIds); c.nodes = c.nodes.filter((n) => !ids.has(n.id)); c.edges = c.edges.filter((e) => !ids.has(e.from) && !ids.has(e.to)); selectedNodeIds = new Set(); } else if (selectedNodeId) { c.nodes = c.nodes.filter((n) => n.id !== selectedNodeId); c.edges = c.edges.filter((e) => e.from !== selectedNodeId && e.to !== selectedNodeId); } else c.edges = c.edges.filter((e) => e.id !== selectedEdgeId); selectedNodeId = null; selectedEdgeId = null; resizeModeNodeId = null; }, "已删除"); }
function beginEdit(id) { commitPendingEdit(); const node = activeCanvas().nodes.find((n) => n.id === id), el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(id)}"] .node-label`); if (!node || !el) return; const histLen = canvasStack(activeCanvas().id).history.length; pushHistory(); editing = { nodeId: id, histLen, before: node.label }; el.contentEditable = "true"; el.focus(); const range = document.createRange(); range.selectNodeContents(el); range.collapse(false); const sel = window.getSelection(); sel?.removeAllRanges(); sel?.addRange(range); }
function finishEdit(el) { if (!editing) return; const value = el.textContent.trim() || "未命名节点"; const changed = value !== editing.before; commitPendingEdit(); render(); if (changed) saveLocal("文字已保存"); }
function cancelEdit() { if (!editing) return; const node = activeCanvas().nodes.find((n) => n.id === editing.nodeId); if (node) node.label = editing.before; const el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(editing.nodeId)}"] .node-label`); if (el) el.contentEditable = "false"; canvasStack(activeCanvas().id).history.length = editing.histLen; editing = null; renderNodes(); updateStatus(); }
function undo() { commitPendingEdit(); finishInspectorEdit(); const c = activeCanvas(); const stack = canvasStack(c.id); if (!stack.history.length) return showToast("没有可撤销的操作"); stack.future.push(canvasSnapshot(c)); const snap = stack.history.pop(); c.nodes = snap.nodes; c.edges = snap.edges; resetSelection(); render(); saveLocal("已撤销"); }
function redo() { commitPendingEdit(); finishInspectorEdit(); const c = activeCanvas(); const stack = canvasStack(c.id); if (!stack.future.length) return showToast("没有可重做的操作"); stack.history.push(canvasSnapshot(c)); const snap = stack.future.pop(); c.nodes = snap.nodes; c.edges = snap.edges; resetSelection(); render(); saveLocal("已重做"); }
function changeZoom(next, cx = viewport.clientWidth / 2, cy = viewport.clientHeight / 2) { const c = activeCanvas(), v = c.view || { zoom: 1, panX: 0, panY: 0 }, before = { x: (cx - v.panX) / v.zoom, y: (cy - v.panY) / v.zoom }; v.zoom = clampZoom(next); v.panX = cx - before.x * v.zoom; v.panY = cy - before.y * v.zoom; clampPan(v); c.view = v; renderTransform(); markDirty(); }
function clampPan(v) { const cw = viewport.clientWidth, ch = viewport.clientHeight, sw = 2400 * v.zoom, sh = 1500 * v.zoom; v.panX = sw <= cw ? (cw - sw) / 2 : clamp(v.panX, cw - sw, 0); v.panY = sh <= ch ? (ch - sh) / 2 : clamp(v.panY, ch - sh, 0); }
function stepZoom(direction) { const v = activeCanvas().view || { zoom: 1 }, isBelowFineThreshold = v.zoom < ZOOM_FINE_THRESHOLD - 1e-9; const delta = direction === "in" ? ZOOM_CLICK_IN : isBelowFineThreshold ? -ZOOM_CLICK_OUT_FINE : -ZOOM_CLICK_OUT_COARSE; changeZoom(v.zoom + delta); }
function resetView() { const c = activeCanvas(); c.view = { zoom: 1, panX: 0, panY: 0 }; renderTransform(); markDirty(); }
function exportWorkflow() { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = "工作流.json"; link.click(); URL.revokeObjectURL(url); showToast("工作流 JSON 已导出（模块库不随文件导出）"); }
function createCanvas() { if (moduleEditing) return showToast(`模块「${moduleEditing.name}」正在编辑中，请先「保存回模块」或「取消编辑」`); const name = window.prompt("请输入新画布名称", `工作流 ${state.canvases.length + 1}`); if (!name?.trim()) return; applyNoHistory(() => { const c = { id: createId("canvas"), name: name.trim(), nodes: [], edges: [], view: { zoom: 1, panX: 0, panY: 0 } }; state.canvases.push(c); state.activeCanvasId = c.id; resetSelection(); }, "新画布已创建"); }
function closeCanvas(id) { if (state.canvases.length === 1) return showToast("至少保留一个画布"); if (moduleEditing && state.activeCanvasId === id) return showToast(`模块「${moduleEditing.name}」正在这个画布上编辑，请先「保存回模块」或「取消编辑」`); const c = state.canvases.find((x) => x.id === id); if (!c || !window.confirm(`关闭“${c.name}”？此画布将被删除，无法撤销。`)) return; applyNoHistory(() => { const index = state.canvases.findIndex((x) => x.id === id); state.canvases = state.canvases.filter((x) => x.id !== id); historyByCanvas.delete(id); if (state.activeCanvasId === id) { state.activeCanvasId = (state.canvases[index] || state.canvases[index - 1] || state.canvases[0]).id; resetSelection(); } }, "画布已关闭"); }
function renameCanvas(id) { const c = state.canvases.find((x) => x.id === id), name = c && window.prompt("请输入画布名称", c.name); if (!c || !name?.trim() || name.trim() === c.name) return; applyNoHistory(() => { c.name = name.trim(); }, "画布名称已更新"); }
function portPoint(n, side) { if (side === "top") return { x: n.x + n.w / 2, y: n.y }; if (side === "right") return { x: n.x + n.w, y: n.y + n.h / 2 }; if (side === "bottom") return { x: n.x + n.w / 2, y: n.y + n.h }; return { x: n.x, y: n.y + n.h / 2 }; }
function updateTemporaryEdge(x, y) { if (!connecting) return; const n = activeCanvas().nodes.find((item) => item.id === connecting.sourceId); if (!n) return; const start = portPoint(n, connecting.side), p = screenToWorld(x, y); temporaryEdge.hidden = false; temporaryEdge.setAttribute("d", curvePath(start.x, start.y, p.x, p.y)); }
function finishConnection(e) { if (!connecting) return; const target = document.elementFromPoint(e.clientX, e.clientY)?.closest?.(".node"), targetId = target?.dataset.nodeId; temporaryEdge.hidden = true; connectorSourceId = null; if (targetId && targetId !== connecting.sourceId) addEdge(connecting.sourceId, targetId); else render(); connecting = null; }
function beginResize(e, nodeId, handle) { if (activeTool !== "select") return; const node = activeCanvas().nodes.find((item) => item.id === nodeId); if (!node) return; e.preventDefault(); e.stopPropagation(); const histLen = canvasStack(activeCanvas().id).history.length; pushHistory(); capturePointer(e.pointerId); resizing = { nodeId, handle, pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, originX: node.x, originY: node.y, originW: node.w, originH: node.h, changed: false, histLen }; }
function updateResize(e) { if (!resizing) return; const node = activeCanvas().nodes.find((item) => item.id === resizing.nodeId), view = activeCanvas().view || { zoom: 1 }; if (!node) return; const dx = (e.clientX - resizing.startX) / view.zoom, dy = (e.clientY - resizing.startY) / view.zoom, handle = resizing.handle, minimum = minSizeForType(node.type), right = resizing.originX + resizing.originW, bottom = resizing.originY + resizing.originH, west = handle.includes("w"), north = handle.includes("n"); let w = resizing.originW, h = resizing.originH, x = resizing.originX, y = resizing.originY; if (handle.includes("e")) w = resizing.originW + dx; if (handle.includes("s")) h = resizing.originH + dy; if (west) w = resizing.originW - dx; if (north) h = resizing.originH - dy; w = Math.max(minimum.w, w); h = Math.max(minimum.h, h); if (west) x = right - w; if (north) y = bottom - h; if (x < 10) { x = 10; if (west) w = Math.max(minimum.w, right - 10); } if (y < 10) { y = 10; if (north) h = Math.max(minimum.h, bottom - 10); } if (x + w > 2400) w = Math.max(minimum.w, 2400 - x); if (y + h > 1500) h = Math.max(minimum.h, 1500 - y); node.x = Math.round(x); node.y = Math.round(y); node.w = Math.round(w); node.h = Math.round(h); if (node.x !== resizing.originX || node.y !== resizing.originY || node.w !== resizing.originW || node.h !== resizing.originH) resizing.changed = true; renderNodes(); renderEdges(); markDirty(); }
function finishResize() { if (!resizing) return; if (!resizing.changed) canvasStack(activeCanvas().id).history.length = resizing.histLen; else saveLocal("节点大小已保存"); resizing = null; render(); }
function cancelResize() { if (!resizing) return; const node = activeCanvas().nodes.find((item) => item.id === resizing.nodeId); if (node) { node.x = resizing.originX; node.y = resizing.originY; node.w = resizing.originW; node.h = resizing.originH; } canvasStack(activeCanvas().id).history.length = resizing.histLen; resizing = null; render(); }
function beginInspectorEdit(field) { if (inspectorEdit?.field === field) return; finishInspectorEdit(); const histLen = canvasStack(activeCanvas().id).history.length; pushHistory(); const node = activeCanvas().nodes.find((item) => item.id === selectedNodeId); inspectorEdit = { field, nodeId: selectedNodeId, before: node ? node[field] : undefined, histLen }; }
function updateInspectorField(field, value) { const nodeId = inspectorEdit?.nodeId ?? selectedNodeId; const node = activeCanvas().nodes.find((item) => item.id === nodeId); if (!node || !["label", "note", "marker"].includes(field)) return; node[field] = value; renderNodes(); updateStatus(); markDirty(); }
function finishInspectorEdit() { if (!inspectorEdit) return; const node = activeCanvas().nodes.find((item) => item.id === inspectorEdit.nodeId); const changed = !!node && node[inspectorEdit.field] !== inspectorEdit.before; if (node) { node.label = node.label.trim() || "未命名节点"; node.note = node.note.trim(); node.marker = DISCUSSION_MARKERS.includes(node.marker) ? node.marker : "待讨论"; } const histLen = inspectorEdit.histLen; inspectorEdit = null; renderNodes(); renderInspector(); updateStatus(); if (changed) saveLocal("节点信息已保存"); else canvasStack(activeCanvas().id).history.length = histLen; }
function blurInspector() { if (inspector.contains(document.activeElement)) document.activeElement.blur(); }

function loadModules() { try { const raw = localStorage.getItem(MODULE_STORAGE_KEY); if (!raw) return []; const arr = JSON.parse(raw); if (!Array.isArray(arr)) return []; return arr.map(normalizeModule).filter(Boolean); } catch { return []; } }
function normalizeModule(m) { if (!m || typeof m.id !== "string" || typeof m.name !== "string") return null; const nodes = Array.isArray(m.nodes) ? m.nodes.map(normalizeNode).filter(Boolean) : []; if (!nodes.length) return null; const ids = new Set(nodes.map((n) => n.id)); const edges = Array.isArray(m.edges) ? m.edges.filter((e) => e && ids.has(e.from) && ids.has(e.to)).map((e) => ({ from: e.from, to: e.to })) : []; return { id: m.id, name: m.name.trim() || "未命名模块", createdAt: m.createdAt, nodes, edges }; }
function saveModules() { try { localStorage.setItem(MODULE_STORAGE_KEY, JSON.stringify(moduleLibrary)); } catch {} }
function capturePointer(pointerId) { try { document.documentElement.setPointerCapture(pointerId); } catch { /* 指针已释放或不受支持，忽略 */ } }
function resetSelection() { selectedNodeId = null; resizeModeNodeId = null; selectedEdgeId = null; connectorSourceId = null; selectedNodeIds = new Set(); connecting = null; temporaryEdge.hidden = true; }
function currentSelectionNodeIds() { if (selectedNodeIds.size) return [...selectedNodeIds]; if (selectedNodeId) return [selectedNodeId]; return []; }
function saveSelectionAsModule() { const ids = currentSelectionNodeIds(); if (!ids.length) return showToast("请先框选或选中要封装的节点"); const canvas = activeCanvas(); const nodes = canvas.nodes.filter((n) => ids.includes(n.id)); if (!nodes.length) return showToast("没有可封装的节点"); const name = window.prompt("给这个模块起个名字（以后可按名字复用）", "流程模块"); if (!name?.trim()) return; const minX = Math.min(...nodes.map((n) => n.x)), minY = Math.min(...nodes.map((n) => n.y)), idSet = new Set(ids); const module = { id: createId("module"), name: name.trim(), createdAt: Date.now(), nodes: nodes.map((n) => ({ id: n.id, type: n.type, x: n.x - minX, y: n.y - minY, w: n.w, h: n.h, label: n.label, note: n.note, marker: n.marker })), edges: canvas.edges.filter((e) => idSet.has(e.from) && idSet.has(e.to)).map((e) => ({ from: e.from, to: e.to })) }; moduleLibrary.push(module); saveModules(); clearModuleEdit(); showToast(`模块「${module.name}」已保存（${module.nodes.length} 个节点、${module.edges.length} 条连线）`); }
function moduleBounds(module) { const minX = Math.min(...module.nodes.map((n) => n.x)), minY = Math.min(...module.nodes.map((n) => n.y)), maxX = Math.max(...module.nodes.map((n) => n.x + n.w)), maxY = Math.max(...module.nodes.map((n) => n.y + n.h)); return { x: minX, y: minY, w: maxX - minX, h: maxY - minY }; }
function viewportCenterWorld() { const r = viewport.getBoundingClientRect(), v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; return { x: (r.width / 2 - v.panX) / v.zoom, y: (r.height / 2 - v.panY) / v.zoom }; }
function placeModule(module, x, y) { const idMap = new Map(); const nodes = module.nodes.map((n) => { const id = createId("node"); idMap.set(n.id, id); return { id, type: n.type, x: clamp(Math.round(x + n.x), 10, Math.max(10, 2400 - n.w)), y: clamp(Math.round(y + n.y), 10, Math.max(10, 1500 - n.h)), w: n.w, h: n.h, label: n.label, note: n.note, marker: n.marker }; }); const edges = module.edges.map((e) => ({ id: createId("edge"), from: idMap.get(e.from), to: idMap.get(e.to) })).filter((e) => e.from && e.to); commit(() => { activeCanvas().nodes.push(...nodes); activeCanvas().edges.push(...edges); selectedNodeId = null; selectedEdgeId = null; connectorSourceId = null; resizeModeNodeId = null; selectedNodeIds = new Set(nodes.map((n) => n.id)); }, `模块「${module.name}」已放置`); nodes.forEach((n) => moduleEditing?.nodeIds.add(n.id)); }
function placeModuleAtCenter(moduleId) { const m = moduleLibrary.find((x) => x.id === moduleId); if (!m) return; const b = moduleBounds(m), c = viewportCenterWorld(); let px = c.x - b.x - b.w / 2 + modulePlaceOffset, py = c.y - b.y - b.h / 2 + modulePlaceOffset; px = clamp(px, 10, Math.max(10, 2400 - b.w)); py = clamp(py, 10, Math.max(10, 1500 - b.h)); modulePlaceOffset = (modulePlaceOffset + 40) % 240; placeModule(m, px, py); closeModuleModal(); }
function clearMultiSelect() { selectedNodeIds = new Set(); render(); updateStatus(); }
function clearModuleEdit() { moduleEditing = null; moduleEditBar.hidden = true; viewport.classList.remove("is-module-editing"); }
function beginModuleEdit(id) { const m = moduleLibrary.find((x) => x.id === id); if (!m) return; if (moduleEditing) { showToast(`正在编辑模块「${moduleEditing.name}」，请先「保存回模块」或「取消编辑」`); return; } const b = moduleBounds(m), c = viewportCenterWorld(); const px = clamp(c.x - b.x - b.w / 2, 10, Math.max(10, 2400 - b.w)), py = clamp(c.y - b.y - b.h / 2, 10, Math.max(10, 1500 - b.h)); const idMap = new Map(); const nodes = m.nodes.map((n) => { const nid = createId("node"); idMap.set(n.id, nid); return { id: nid, type: n.type, x: clamp(Math.round(px + n.x), 10, Math.max(10, 2400 - n.w)), y: clamp(Math.round(py + n.y), 10, Math.max(10, 1500 - n.h)), w: n.w, h: n.h, label: n.label, note: n.note, marker: n.marker }; }); const edges = m.edges.map((e) => ({ id: createId("edge"), from: idMap.get(e.from), to: idMap.get(e.to) })).filter((e) => e.from && e.to); moduleEditing = { id: m.id, name: m.name, nodeIds: new Set(nodes.map((n) => n.id)) };
if (activeTool !== "select") setTool("select"); commit(() => { activeCanvas().nodes.push(...nodes); activeCanvas().edges.push(...edges); resetSelection(); selectedNodeIds = new Set(nodes.map((n) => n.id)); }, `模块「${m.name}」已打开，改完点「保存回模块」`); closeModuleModal(); }
function saveModuleEdit() { if (!moduleEditing) return; const m = moduleLibrary.find((x) => x.id === moduleEditing.id); if (!m) return clearModuleEdit(), showToast("原模块已不存在，编辑已退出"); const canvas = activeCanvas(); const nodes = canvas.nodes.filter((n) => moduleEditing.nodeIds.has(n.id)); if (!nodes.length) return showToast("模块内容已被删空。若确实想清空，请直接删除该模块；或先「取消编辑」"); const ids = new Set(nodes.map((n) => n.id)); const minX = Math.min(...nodes.map((n) => n.x)), minY = Math.min(...nodes.map((n) => n.y)); m.nodes = nodes.map((n) => ({ id: n.id, type: n.type, x: n.x - minX, y: n.y - minY, w: n.w, h: n.h, label: n.label, note: n.note, marker: n.marker })); m.edges = canvas.edges.filter((e) => ids.has(e.from) && ids.has(e.to)).map((e) => ({ from: e.from, to: e.to })); saveModules(); clearModuleEdit(); renderModules(); showToast(`模块「${m.name}」已更新（${m.nodes.length} 个节点、${m.edges.length} 条连线）`); }
function cancelModuleEdit() { if (!moduleEditing) return; const name = moduleEditing.name; clearModuleEdit(); render(); showToast(`已退出模块「${name}」的编辑，原模块未改动`); }
function toggleMultiSelect(id) { const set = new Set(selectedNodeIds); if (!set.size && selectedNodeId) set.add(selectedNodeId); set.has(id) ? set.delete(id) : set.add(id); selectedNodeIds = set; selectedNodeId = null; selectedEdgeId = null; connectorSourceId = null; resizeModeNodeId = null; render(); updateStatus(); }
function deleteModule(id) { const m = moduleLibrary.find((x) => x.id === id); if (!m) return; if (moduleEditing?.id === id) return showToast(`模块「${m.name}」正在编辑中，请先「保存回模块」或「取消编辑」`); if (!window.confirm(`删除模块「${m.name}」？删除后无法恢复。`)) return; moduleLibrary = moduleLibrary.filter((x) => x.id !== id); saveModules(); renderModules(); showToast(`模块「${m.name}」已删除`); }
function renameModule(id) { const m = moduleLibrary.find((x) => x.id === id); const name = m && window.prompt("给模块起个新名字", m.name); if (!m || !name?.trim() || name.trim() === m.name) return; m.name = name.trim(); if (moduleEditing?.id === id) { moduleEditing.name = m.name; renderModuleEditBar(); } saveModules(); renderModules(); showToast("模块已重命名"); }
function formatModuleTime(ts) { if (!Number.isFinite(ts)) return ""; const d = new Date(ts), pad = (n) => String(n).padStart(2, "0"); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`; }
function renderModules() { moduleList.innerHTML = ""; if (!moduleLibrary.length) { const empty = document.createElement("p"); empty.className = "module-empty"; empty.textContent = "模块库还是空的。先在画布上选中或框选几个节点，点「封装为模块」把它存进来。"; moduleList.append(empty); return; } moduleLibrary.forEach((m) => { const item = document.createElement("div"); item.className = "module-item"; item.dataset.moduleId = m.id; const time = formatModuleTime(m.createdAt); const meta = `${m.nodes.length} 个节点 · ${m.edges.length} 条连线${time ? ` · 保存于 ${time}` : ""}`; item.innerHTML = `<div class="module-item-info"><div class="module-item-name"></div><div class="module-item-meta"></div></div><div class="module-item-actions"><button class="text-button" type="button" data-module-action="edit" title="把模块铺到当前画布上打开修改，改完存回原模块">编辑</button><button class="text-button" type="button" data-module-action="place" title="把模块放置到当前画布中心">放置</button><button class="text-button" type="button" data-module-action="rename" title="重命名模块">改名</button><button class="text-button module-delete" type="button" data-module-action="delete" title="删除模块">删除</button></div>`; item.querySelector(".module-item-name").textContent = m.name; item.querySelector(".module-item-meta").textContent = meta; moduleList.append(item); }); }
function openModuleModal() { renderModules(); lastModalTrigger = document.activeElement; moduleModal.hidden = false; moduleModal.querySelector("button")?.focus(); }
function closeModuleModal() { moduleModal.hidden = true; if (lastModalTrigger && document.contains(lastModalTrigger)) lastModalTrigger.focus(); }
function trapTabInModal(e) { const focusables = [...moduleModal.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')].filter((el) => !el.disabled && el.offsetParent !== null); if (!focusables.length) { e.preventDefault(); return; } const first = focusables[0], last = focusables[focusables.length - 1], current = document.activeElement; if (!current || !moduleModal.contains(current)) { e.preventDefault(); (e.shiftKey ? last : first).focus(); return; } if (e.shiftKey && current === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && current === last) { e.preventDefault(); first.focus(); } }
function startMarquee(e) { const p = screenToWorld(e.clientX, e.clientY); marqueeDrag = { pointerId: e.pointerId, startWorld: p, currentWorld: p }; marquee.hidden = false; }
function updateMarquee(e) { if (!marqueeDrag) return; const p = screenToWorld(e.clientX, e.clientY); marqueeDrag.currentWorld = p; const a = marqueeDrag.startWorld, b = p, left = Math.min(a.x, b.x), top = Math.min(a.y, b.y); marquee.style.left = `${left}px`; marquee.style.top = `${top}px`; marquee.style.width = `${Math.abs(b.x - a.x)}px`; marquee.style.height = `${Math.abs(b.y - a.y)}px`; }
function finishMarquee() { if (!marqueeDrag) return; const a = marqueeDrag.startWorld, b = marqueeDrag.currentWorld, left = Math.min(a.x, b.x), top = Math.min(a.y, b.y), right = Math.max(a.x, b.x), bottom = Math.max(a.y, b.y); marqueeDrag = null; marquee.hidden = true; marquee.style.width = "0px"; marquee.style.height = "0px"; const selected = activeCanvas().nodes.filter((n) => n.x < right && n.x + n.w > left && n.y < bottom && n.y + n.h > top).map((n) => n.id); selectedNodeIds = new Set(selected); selectedNodeId = null; selectedEdgeId = null; connectorSourceId = null; resizeModeNodeId = null; render(); updateStatus(); }
function cancelMarquee() { if (!marqueeDrag) return; marqueeDrag = null; marquee.hidden = true; marquee.style.width = "0px"; marquee.style.height = "0px"; }

document.querySelectorAll(".tool-button").forEach((b) => b.addEventListener("click", () => setTool(b.dataset.tool)));
document.querySelector(".topbar-groups").addEventListener("click", (e) => { const a = e.target.closest("[data-action]")?.dataset.action; if (a === "undo") undo(); if (a === "redo") redo(); if (a === "export") exportWorkflow(); if (a === "save") { saveLocal(); showToast("已保存到本机"); } if (a === "save-module") saveSelectionAsModule(); if (a === "open-modules") openModuleModal(); });
document.querySelector(".statusbar").addEventListener("click", (e) => { const a = e.target.closest("[data-action]")?.dataset.action; if (a === "zoom-out") stepZoom("out"); if (a === "zoom-in") stepZoom("in"); if (a === "zoom-reset") resetView(); });
canvasTabs.addEventListener("click", (e) => { const add = e.target.closest('[data-action="new-canvas"]'), close = e.target.closest(".tab-close"), tab = e.target.closest(".canvas-tab"); if (add) return createCanvas(); if (!tab) return; if (close) return closeCanvas(tab.dataset.canvasId); if (state.activeCanvasId === tab.dataset.canvasId) return; if (moduleEditing) return showToast(`模块「${moduleEditing.name}」正在编辑中，请先「保存回模块」或「取消编辑」`); state.activeCanvasId = tab.dataset.canvasId; resetSelection(); render(); markDirty(); });
canvasTabs.addEventListener("dblclick", (e) => { const tab = e.target.closest(".canvas-tab"); if (tab && !e.target.closest(".tab-close")) renameCanvas(tab.dataset.canvasId); });
inspector.addEventListener("focusin", (e) => { const field = e.target.closest("[name]")?.name; if (field) beginInspectorEdit(field); });
inspector.addEventListener("input", (e) => { const field = e.target.closest("[name]")?.name; if (field) updateInspectorField(field, e.target.value); });
inspector.addEventListener("change", (e) => { if (!e.target.matches("[name]")) return; updateInspectorField(e.target.name, e.target.value); finishInspectorEdit(); });
inspector.addEventListener("focusout", (e) => { if (e.target.matches("[name]")) window.setTimeout(() => { if (!inspector.contains(document.activeElement)) finishInspectorEdit(); }, 0); });
inspector.addEventListener("click", (e) => { const target = e.target.closest("[data-inspect-node-id]"); if (!target) return; selectedNodeId = target.dataset.inspectNodeId; selectedEdgeId = null; connectorSourceId = null; selectedNodeIds = new Set(); render(); });
importInput.addEventListener("change", async () => { const file = importInput.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()); if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.canvases) || parsed.canvases.length === 0) { showToast("导入失败：文件不是有效的工作流 JSON"); return; } commitPendingEdit(); finishInspectorEdit(); state = normalizeState(parsed); historyByCanvas.clear(); resetSelection(); render(); saveLocal("已导入工作流"); clearModuleEdit(); resetSelection(); render(); showToast("工作流已导入"); } catch { showToast("导入失败：文件不是有效的工作流 JSON"); } finally { importInput.value = ""; } });

multiSelectPanel.addEventListener("click", (e) => { const a = e.target.closest("[data-action]")?.dataset.action; if (a === "save-module") saveSelectionAsModule(); if (a === "clear-multi-select") clearMultiSelect(); });
moduleEditBar.addEventListener("click", (e) => { const a = e.target.closest("[data-action]")?.dataset.action; if (a === "save-module-edit") saveModuleEdit(); if (a === "cancel-module-edit") cancelModuleEdit(); });
moduleModal.addEventListener("click", (e) => { const action = e.target.closest("[data-action]")?.dataset.action; if (action === "close-modules") return closeModuleModal(); if (e.target.closest(".modal-backdrop") && !e.target.closest(".modal")) return closeModuleModal(); const btn = e.target.closest("[data-module-action]"); if (!btn) return; const id = btn.closest(".module-item")?.dataset.moduleId; if (!id) return; const mAction = btn.dataset.moduleAction; if (mAction === "place") placeModuleAtCenter(id); if (mAction === "rename") renameModule(id); if (mAction === "delete") deleteModule(id); if (mAction === "edit") beginModuleEdit(id); });
nodeLayer.addEventListener("click", (e) => { const resizeToggle = e.target.closest(".resize-toggle"); if (!resizeToggle) return; e.preventDefault(); e.stopPropagation(); if (activeTool !== "select") setTool("select"); resizeModeNodeId = resizeModeNodeId === resizeToggle.dataset.nodeId ? null : resizeToggle.dataset.nodeId; renderNodes(); updateStatus(); });
nodeLayer.addEventListener("pointerdown", (e) => { blurInspector(); const labelTarget = e.target.closest(".node-label"); if (labelTarget) { const labelNode = e.target.closest(".node"), labelId = labelNode?.dataset.nodeId, now = Date.now(); if (activeTool === "connector") { lastLabelClick = null; } else if (editing && editing.nodeId === labelId) { return; } else if (lastLabelClick && lastLabelClick.nodeId === labelId && now - lastLabelClick.time < 400) { lastLabelClick = null; e.preventDefault(); e.stopPropagation(); beginEdit(labelId); return; } else { lastLabelClick = { nodeId: labelId, time: now }; } } else { lastLabelClick = null; } const resizeToggle = e.target.closest(".resize-toggle"); if (resizeToggle) { e.preventDefault(); e.stopPropagation(); return; } const resizeHandle = e.target.closest(".resize-handle"); if (resizeHandle) return beginResize(e, resizeHandle.dataset.nodeId, resizeHandle.dataset.handle); const port = e.target.closest(".port"), el = e.target.closest(".node"); if (!el) return; const id = el.dataset.nodeId; if (port) { e.preventDefault(); e.stopPropagation(); resizeModeNodeId = null; connecting = { sourceId: id, side: port.dataset.side, pointerId: e.pointerId }; connectorSourceId = id; updateTemporaryEdge(e.clientX, e.clientY); renderNodes(); capturePointer(e.pointerId); return; } if (activeTool === "connector") { e.preventDefault(); if (!connectorSourceId) { connectorSourceId = id; selectedNodeId = id; resizeModeNodeId = null; selectedEdgeId = null; selectedNodeIds = new Set(); render(); } else { addEdge(connectorSourceId, id); connectorSourceId = null; } return; } if (e.shiftKey && (activeTool === "select" || activeTool === "marquee")) { e.preventDefault(); toggleMultiSelect(id); return; } if (activeTool !== "select") return; e.preventDefault(); const groupIds = selectedNodeIds.size && selectedNodeIds.has(id) ? [...selectedNodeIds] : [id], groupNodes = activeCanvas().nodes.filter((x) => groupIds.includes(x.id)); selectedNodeId = groupIds.length === 1 ? id : null; resizeModeNodeId = null; selectedEdgeId = null; selectedNodeIds = groupIds.length === 1 ? new Set() : new Set(groupIds); const histLen = canvasStack(activeCanvas().id).history.length; drag = { nodeId: id, pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, items: groupNodes.map((x) => ({ id: x.id, originX: x.x, originY: x.y })), changed: false, histLen }; pushHistory(); renderNodes(); renderEdges(); capturePointer(e.pointerId); renderInspector(); updateStatus(); });
nodeLayer.addEventListener("focusout", (e) => { if (e.target.matches(".node-label[contenteditable='true']")) finishEdit(e.target); });
edgeGroup.addEventListener("click", (e) => { const edge = e.target.closest(".edge"); if (!edge) return; selectedEdgeId = edge.dataset.edgeId; selectedNodeId = null; selectedNodeIds = new Set(); resizeModeNodeId = null; renderNodes(); renderEdges(); renderInspector(); updateStatus(); });
viewport.addEventListener("pointerdown", (e) => { blurInspector(); if (connecting) return; if (activeTool === "marquee") { if (e.button !== 0) return; e.preventDefault(); startMarquee(e); return; } if (e.target.closest?.(".node") || e.target.closest?.("button") || e.target.closest?.(".module-edit-bar")) return; if (e.target.closest?.(".edge")) return; if (editing) { commitPendingEdit(); render(); return; } if (activeTool !== "select" && activeTool !== "connector") { if (e.button === 0) { e.preventDefault(); addNode(activeTool, e.clientX, e.clientY); } return; } if (e.button !== 0 && e.button !== 1) return; if (selectedNodeId || selectedEdgeId || selectedNodeIds.size || resizeModeNodeId || connectorSourceId) { resetSelection(); render(); } e.preventDefault(); const v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; pan = { pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, originX: v.panX, originY: v.panY }; viewport.classList.add("is-panning"); });
document.addEventListener("pointermove", (e) => { if (connecting) return updateTemporaryEdge(e.clientX, e.clientY); if (marqueeDrag) return updateMarquee(e); if (resizing) return updateResize(e); if (drag) { const v = activeCanvas().view || { zoom: 1 }, canvas = activeCanvas(), dx = (e.clientX - drag.startX) / v.zoom, dy = (e.clientY - drag.startY) / v.zoom; let moved = false; drag.items.forEach((item) => { const n = canvas.nodes.find((x) => x.id === item.id); if (!n) return; n.x = clamp(Math.round(item.originX + dx), 10, Math.max(10, 2400 - n.w)); n.y = clamp(Math.round(item.originY + dy), 10, Math.max(10, 1500 - n.h)); if (n.x !== item.originX || n.y !== item.originY) moved = true; }); if (moved) drag.changed = true; renderNodes(); renderEdges(); markDirty(); } if (pan) { const v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; v.panX = pan.originX + e.clientX - pan.startX; v.panY = pan.originY + e.clientY - pan.startY; clampPan(v); activeCanvas().view = v; renderTransform(); markDirty(); } });
document.addEventListener("pointerup", (e) => { if (connecting) return finishConnection(e); if (marqueeDrag) return finishMarquee(); if (resizing) return finishResize(); if (drag) { if (!drag.changed) canvasStack(activeCanvas().id).history.length = drag.histLen; else saveLocal("节点位置已保存"); drag = null; render(); } if (pan) { pan = null; viewport.classList.remove("is-panning"); } });
document.addEventListener("pointercancel", () => { if (drag) { if (!drag.changed) canvasStack(activeCanvas().id).history.length = drag.histLen; drag = null; } cancelResize(); cancelMarquee(); pan = null; connecting = null; connectorSourceId = null; temporaryEdge.hidden = true; viewport.classList.remove("is-panning"); render(); });
// 兜底：指针捕获被系统回收（例如指针设备拔出、浏览器强制释放）时，把进行中的交互状态收干净，避免虚线粘在光标上。
document.addEventListener("lostpointercapture", (e) => { if (connecting && connecting.pointerId === e.pointerId) { connecting = null; connectorSourceId = null; temporaryEdge.hidden = true; render(); return; } if (resizing && resizing.pointerId === e.pointerId) return cancelResize(); if (drag && drag.pointerId === e.pointerId) { if (!drag.changed) canvasStack(activeCanvas().id).history.length = drag.histLen; drag = null; render(); return; } if (marqueeDrag && marqueeDrag.pointerId === e.pointerId) { cancelMarquee(); render(); return; } if (pan && pan.pointerId === e.pointerId) { pan = null; viewport.classList.remove("is-panning"); } });
viewport.addEventListener("wheel", (e) => { e.preventDefault(); const v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; if (e.ctrlKey || e.metaKey) changeZoom(v.zoom + (e.deltaY > 0 ? -.08 : .08), e.clientX - viewport.getBoundingClientRect().left, e.clientY - viewport.getBoundingClientRect().top); else { const unit = e.deltaMode === 1 ? 16 : e.deltaMode === 2 ? viewport.clientHeight : 1; v.panX -= e.deltaX * unit; v.panY -= e.deltaY * unit; clampPan(v); activeCanvas().view = v; renderTransform(); markDirty(); } }, { passive: false });
viewport.addEventListener("dblclick", (e) => { if (!e.target.closest?.(".node, .port") && activeTool === "text") addNode("text", e.clientX, e.clientY); });
document.addEventListener("keydown", (e) => { if (editing) { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z") { e.preventDefault(); cancelEdit(); return; } if (e.key === "Escape") { e.preventDefault(); cancelEdit(); return; } if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); e.target.blur(); } return; } if (focusInEditableControl()) return; if (!moduleModal.hidden) { if (e.key === "Escape") { e.preventDefault(); closeModuleModal(); return; } if (e.key === "Tab") { trapTabInModal(e); return; } if ((e.ctrlKey || e.metaKey) && ["z", "y", "s"].includes(e.key.toLowerCase())) { e.preventDefault(); return; } return; } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z") { e.preventDefault(); undo(); return; } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "y") { e.preventDefault(); redo(); return; } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "s") { e.preventDefault(); saveLocal(); showToast("已保存到本机"); return; } if (e.key === "Escape") { if (marqueeDrag) return cancelMarquee(); if (resizing) return cancelResize(); if (connecting || selectedNodeId || selectedEdgeId || selectedNodeIds.size || resizeModeNodeId || connectorSourceId) { resetSelection(); render(); return; } if (moduleEditing && window.confirm(`退出模块「${moduleEditing.name}」的编辑？画布上这份内容会留着，原模块不改动。`)) return cancelModuleEdit(); return; } if (e.ctrlKey || e.metaKey || e.altKey) return; if (e.key.toLowerCase() === "m") { setTool("marquee"); return; } if (e.key === "Delete" || e.key === "Backspace") deleteSelection(); if (e.key.toLowerCase() === "v") setTool("select"); if (e.key.toLowerCase() === "t") setTool("text"); });
window.addEventListener("pagehide", flushPendingSave);
window.addEventListener("beforeunload", flushPendingSave);
render(); saveStatus.textContent = hasSavedDraft() ? "已从本机恢复" : "尚未保存";
