/* ============================================================================
   检查器卷（拆分自原 app.js，内容逐字照搬，未改一行逻辑）

   这一份文件管「右侧节点信息面板」：
     1. 关系列表——按方向查出前置/后续节点（relationNodes）、渲染关系列表（renderRelationList）；
     2. 面板渲染——renderInspector（节点态 / 连线态 / 框选态三种视图的切换与填值）；
     3. 面板读写——beginInspectorEdit（开始编辑，记快照）、updateInspectorField（逐字段写回）、
        finishInspectorEdit（提交、去空格截断、未变则回滚）。

   ⚠ 加载顺序：constants.js → storage.js → state.js → canvas.js → node.js → edge.js → **本文件** → … → app.js
   本文件**只声明函数、不在顶层执行任何语句**，所以放在 app.js 之前即可；
   它调用 node.js 的 markerClass、edge.js 的 renderEdges、app.js 的 render / saveLocal、state.js 的 pushHistory 等，
   都发生在被调用的那一刻，那时全部脚本都已加载完。
   ——反过来说：**往这里加顶层执行语句之前，先回来看这一段**。
   ============================================================================ */

/* ---- 关系列表 ---- */

function relationNodes(nodeId, direction) { const canvas = activeCanvas(), ids = canvas.edges.filter((edge) => direction === "previous" ? edge.to === nodeId : edge.from === nodeId).map((edge) => direction === "previous" ? edge.from : edge.to); return ids.map((id) => canvas.nodes.find((node) => node.id === id)).filter(Boolean); }
function renderRelationList(container, nodes, emptyText) { container.innerHTML = ""; if (!nodes.length) { const empty = document.createElement("span"); empty.className = "relation-empty"; empty.textContent = emptyText; container.append(empty); return; } nodes.forEach((node) => { const button = document.createElement("button"); button.type = "button"; button.className = "relation-item"; button.dataset.inspectNodeId = node.id; button.title = `选择${node.label}`; button.textContent = node.label; container.append(button); }); }

/* 循环回边勾选后：目标/相关菱形没填 exitCondition → 检查器显式警告，别让人以为勾了 loop 就算有结束标准。 */
function updateLoopExitWarning(edge, canvas) {
  if (!loopExitWarning) return;
  if (!edge || edge.loop !== true) { loopExitWarning.hidden = true; loopExitWarning.textContent = ""; return; }
  const info = loopExitConditionText(edge, canvas);
  if (info.filled) { loopExitWarning.hidden = true; loopExitWarning.textContent = ""; return; }
  loopExitWarning.hidden = false;
  loopExitWarning.textContent = info.diamond
    ? "循环结束条件未填写：请在判断节点填写退出循环条件"
    : "循环结束条件未填写：请在目标/相关判断（菱形）节点填写退出循环条件";
}

/* ---- 面板渲染 ---- */

function renderInspector() { const node = activeCanvas().nodes.find((item) => item.id === selectedNodeId), edge = selectedEdgeId ? activeCanvas().edges.find((item) => item.id === selectedEdgeId) : null; if (selectedNodeIds.size) { const c = activeCanvas(), internal = c.edges.filter((e) => selectedNodeIds.has(e.from) && selectedNodeIds.has(e.to)).length; inspectorEmpty.hidden = true; inspectorForm.hidden = true; inspectorEdgeForm.hidden = true; multiSelectPanel.hidden = false; inspectorCount.textContent = `${selectedNodeIds.size} 个节点`; multiSelectSummary.textContent = `已框选 ${selectedNodeIds.size} 个节点、${internal} 条内部连线。可封装为模块，以后在任意画布复用。`; return; } multiSelectPanel.hidden = true; inspectorEmpty.hidden = Boolean(node || edge); if (!node && !edge) { inspectorName.value = ""; inspectorNote.value = ""; inspectorCondition.value = ""; inspectorExitCondition.value = ""; inspectorEdgeName.value = ""; if (loopExitWarning) { loopExitWarning.hidden = true; loopExitWarning.textContent = ""; } } inspectorForm.hidden = !node; inspectorEdgeForm.hidden = !edge; inspectorCount.textContent = node ? "1 个节点" : edge ? "1 条连线" : "未选择"; if (node) { inspectorName.value = node.label; inspectorNote.value = node.note; inspectorType.value = NODE_TYPE_LABELS[node.type] || node.type; inspectorMarker.value = DISCUSSION_MARKERS.includes(node.marker) ? node.marker : "待讨论"; inspectorCondition.value = node.condition || ""; inspectorExitCondition.value = node.exitCondition || ""; conditionGroup.hidden = node.type !== "diamond"; exitConditionGroup.hidden = node.type !== "diamond"; if (loopExitWarning) { loopExitWarning.hidden = true; loopExitWarning.textContent = ""; } const previous = relationNodes(node.id, "previous"), next = relationNodes(node.id, "next"); previousCount.textContent = String(previous.length); nextCount.textContent = String(next.length); renderRelationList(previousNodes, previous, "无前置节点"); renderRelationList(nextNodes, next, "无后续节点"); } else if (edge) { inspectorEdgeName.value = edge.label || ""; inspectorEdgeLoop.checked = edge.loop === true; const fromNode = activeCanvas().nodes.find((n) => n.id === edge.from), isBranch = fromNode?.type === "diamond"; branchGroup.hidden = !isBranch; edgeNameLabel.textContent = "连线名称"; inspectorEdgeName.placeholder = "例如：审批、依赖、下一步"; inspector.querySelectorAll(".branch-button").forEach((btn) => btn.classList.toggle("is-active", btn.dataset.branch === edge.branch)); inspector.querySelectorAll(".width-button").forEach((btn) => btn.classList.toggle("is-active", btn.dataset.width === (edge.width || "medium"))); inspector.querySelectorAll(".color-swatch").forEach((sw) => sw.classList.toggle("is-active", (edge.color || DEFAULT_EDGE_COLOR) === sw.dataset.color)); updateLoopExitWarning(edge, activeCanvas()); } }

/* ---- 面板读写 ---- */

function beginInspectorEdit(field) { const isEdge = field === "edgeLabel" || field === "loop", id = isEdge ? selectedEdgeId : selectedNodeId; if (inspectorEdit?.field === field && inspectorEdit.nodeId === id) return; const target = isEdge ? activeCanvas().edges.find((e) => e.id === id) : activeCanvas().nodes.find((item) => item.id === id); const before = target ? (field === "loop" ? !!target.loop : field === "edgeLabel" ? target.label : target[field]) : undefined; inspectorEdit = { field, nodeId: id, kind: isEdge ? "edge" : "node", before, touched: false, token: null }; }
function updateInspectorField(field, value) { const _tid = (field === "edgeLabel" || field === "loop") ? selectedEdgeId : selectedNodeId; if (!inspectorEdit || inspectorEdit.field !== field || inspectorEdit.nodeId !== _tid) beginInspectorEdit(field); if (field === "edgeLabel") { const edge = activeCanvas().edges.find((e) => e.id === selectedEdgeId); if (!edge) return; if (inspectorEdit && inspectorEdit.kind === "edge" && inspectorEdit.nodeId === selectedEdgeId && inspectorEdit.field === "edgeLabel" && !inspectorEdit.touched && edge.label !== value) { inspectorEdit.token = pushHistory(); inspectorEdit.touched = true; } edge.label = value; renderEdges(); updateStatus(); markDirty(); return; } if (field === "loop") { const edge = activeCanvas().edges.find((e) => e.id === selectedEdgeId); if (!edge) return; const next = !!value; if (inspectorEdit && inspectorEdit.kind === "edge" && inspectorEdit.nodeId === selectedEdgeId && inspectorEdit.field === "loop" && !inspectorEdit.touched && edge.loop !== next) { inspectorEdit.token = pushHistory(); inspectorEdit.touched = true; } edge.loop = next; renderEdges(); updateLoopExitWarning(edge, activeCanvas()); updateStatus(); markDirty(); return; } const node = activeCanvas().nodes.find((item) => item.id === selectedNodeId); if (!node || !["label", "note", "marker", "condition", "exitCondition"].includes(field)) return; if (inspectorEdit && inspectorEdit.nodeId === selectedNodeId && inspectorEdit.field === field && !inspectorEdit.touched && node[field] !== value) { inspectorEdit.token = pushHistory(); inspectorEdit.touched = true; } node[field] = value; if (field === "condition" || field === "exitCondition") { markDirty(); return; } const el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(node.id)}"]`); if (el) { if (field === "label") el.querySelector(".node-label").textContent = node.label; else if (field === "note") { const noteEl = el.querySelector(".node-note"); noteEl.textContent = node.note; noteEl.hidden = !node.note; } else if (field === "marker") { const markerEl = el.querySelector(".node-marker"); markerEl.textContent = node.marker; markerEl.className = `node-marker ${markerClass(node.marker)}`; } } renderEdges(); updateStatus(); markDirty(); }
function finishInspectorEdit() { if (!inspectorEdit) return; const isEdge = inspectorEdit.kind === "edge", field = inspectorEdit.field, before = inspectorEdit.before, touched = inspectorEdit.touched, token = inspectorEdit.token; let unchanged = false; if (isEdge) { const edge = activeCanvas().edges.find((e) => e.id === inspectorEdit.nodeId); if (edge) { if (field === "loop") { unchanged = touched && edge && edge.loop === before; } else { edge.label = (edge.label || "").trim().slice(0, 80); unchanged = touched && edge && edge.label === before; } } } else { const node = activeCanvas().nodes.find((item) => item.id === inspectorEdit.nodeId); if (node) { node.label = (node.label.trim() || "未命名节点").slice(0, 80); node.note = node.note.trim().slice(0, 240); node.marker = DISCUSSION_MARKERS.includes(node.marker) ? node.marker : "待讨论"; node.condition = (node.condition || "").trim().slice(0, 80); node.exitCondition = (node.exitCondition || "").trim().slice(0, 80); unchanged = touched && node && node[field] === before; } } inspectorEdit = null; render(); if (unchanged) { if (token != null) popRollback(token); } else if (touched) saveLocal(isEdge ? (field === "loop" ? "循环回边已保存" : "连线名称已保存") : "节点信息已保存"); }
