/* ============================================================================
   模块卷（拆分自原 app.js，内容逐字照搬，未改一行逻辑）

   这一份文件管「组合模块」：把若干节点封装成可复用模块、存进本机模块库、再放回任意画布。
     1. 模块库导出导入——moduleLibraryPayload / exportModuleLibrary / importModuleLibraryFile（丙方案：模块库单独成文件）；
     2. 模块库渲染与弹窗——renderModules / openModuleModal / closeModuleModal / trapTabInModal；
     3. 就地编辑——renderModuleEditBar / clearModuleEdit / beginModuleEdit / saveModuleEdit / cancelModuleEdit；
     4. 放置与封装——placeModule / placeModuleAtCenter / moduleBounds / viewportCenterWorld / saveSelectionAsModule；
     5. 删除与重命名——deleteModule / renameModule / formatModuleTime。

   ⚠ 加载顺序：constants.js → storage.js → state.js → canvas.js → node.js → edge.js → inspector.js → ai-bridge.js → **本文件** → app.js
   本文件**只声明函数、不在顶层执行任何语句**，所以放在 app.js 之前即可；
   它调用 app.js 的 render / showToast / setTool、state.js 的 commit / createId / normalizeModule 等，
   都发生在被调用的那一刻，那时全部脚本都已加载完。
   saveSelectionAsModule 会调用 currentSelectionNodeIds（在 marquee 卷里，稍后拆出），同为事件时调用，无先后问题。
   ——反过来说：**往这里加顶层执行语句之前，先回来看这一段**。
   ============================================================================ */

/* ---- 模块库导出导入 ---- */

function moduleLibraryPayload() { return { kind: MODULE_FILE_KIND, version: 1, exportedAt: Date.now(), modules: moduleLibrary.map((m) => ({ id: m.id, name: m.name, createdAt: m.createdAt, nodes: m.nodes, edges: m.edges })) }; }
function exportModuleLibrary() { if (!moduleLibrary.length) return showToast("模块库还是空的，没有可导出的模块"); const blob = new Blob([JSON.stringify(moduleLibraryPayload(), null, 2)], { type: "application/json" }), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = `模块库-${moduleLibrary.length}个模块.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); showToast(`模块库已导出（${moduleLibrary.length} 个模块）`); }
async function importModuleLibraryFile(file) { if (!file) return; if (moduleEditing) return showToast(`模块「${moduleEditing.name}」正在编辑中，请先「保存回模块」或「取消编辑」`); try { if (file.size > MAX_MODULE_FILE_BYTES) return showToast("模块库导入失败：文件过大（超过 8MB）"); const text = (await file.text()).replace(/^\uFEFF/, ""), parsed = JSON.parse(text); if (!parsed || typeof parsed !== "object" || parsed.kind !== MODULE_FILE_KIND || !Array.isArray(parsed.modules)) return showToast(Array.isArray(parsed?.canvases) ? "模块库导入失败：这是画布工作流文件，请改用顶栏的「导入」按钮" : "模块库导入失败：文件不是有效的模块库 JSON"); if (typeof parsed.version === "number" && parsed.version > 1 && !window.confirm("该文件由更新版本导出，可能包含当前版本无法识别的内容，仍要导入吗？")) return; const incoming = parsed.modules.map(normalizeModule).filter(Boolean), skipped = parsed.modules.length - incoming.length; if (!incoming.length) return showToast("模块库导入失败：文件里没有可用的模块"); const overwrite = incoming.filter((m) => moduleLibrary.some((x) => x.id === m.id)).length, added = incoming.length - overwrite; if (!window.confirm(`导入将与本机模块库合并：新增 ${added} 个、覆盖同 id ${overwrite} 个（本机其他模块不受影响）。${skipped > 0 ? `文件里有 ${skipped} 条无法识别，将被忽略。` : ""}是否继续？`)) return; incoming.forEach((m) => { const i = moduleLibrary.findIndex((x) => x.id === m.id); if (i >= 0) moduleLibrary[i] = m; else moduleLibrary.push(m); }); saveModules(); renderModules(); showToast(`模块库已导入：新增 ${added} 个、覆盖 ${overwrite} 个`); } catch { showToast("模块库导入失败：文件不是有效的模块库 JSON"); } }

/* ---- 模块库渲染与弹窗 ---- */

function renderModules() { moduleList.innerHTML = ""; if (!moduleLibrary.length) { const empty = document.createElement("p"); empty.className = "module-empty"; empty.textContent = "模块库还是空的。先在画布上选中或框选几个节点，点「封装为模块」把它存进来。"; moduleList.append(empty); return; } moduleLibrary.forEach((m) => { const item = document.createElement("div"); item.className = "module-item"; item.dataset.moduleId = m.id; const time = formatModuleTime(m.createdAt); const meta = `${m.nodes.length} 个节点 · ${m.edges.length} 条连线${time ? ` · 保存于 ${time}` : ""}`; item.innerHTML = `<div class="module-item-info"><div class="module-item-name"></div><div class="module-item-meta"></div></div><div class="module-item-actions"><button class="text-button" type="button" data-module-action="edit" title="把模块铺到当前画布上打开修改，改完存回原模块">编辑</button><button class="text-button" type="button" data-module-action="place" title="把模块放置到当前画布中心">放置</button><button class="text-button" type="button" data-module-action="rename" title="重命名模块">改名</button><button class="text-button module-delete" type="button" data-module-action="delete" title="删除模块">删除</button></div>`; item.querySelector(".module-item-name").textContent = m.name; item.querySelector(".module-item-meta").textContent = meta; moduleList.append(item); }); }
function openModuleModal() { renderModules(); lastModalTrigger = document.activeElement; moduleModal.hidden = false; moduleModal.querySelector("button")?.focus(); }
function closeModuleModal() { moduleModal.hidden = true; if (lastModalTrigger && document.contains(lastModalTrigger)) lastModalTrigger.focus(); }
function trapTabInModal(e) { const focusables = [...moduleModal.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')].filter((el) => !el.disabled && el.offsetParent !== null); if (!focusables.length) { e.preventDefault(); return; } const first = focusables[0], last = focusables[focusables.length - 1], current = document.activeElement; if (!current || !moduleModal.contains(current)) { e.preventDefault(); (e.shiftKey ? last : first).focus(); return; } if (e.shiftKey && current === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && current === last) { e.preventDefault(); first.focus(); } }

/* ---- 就地编辑 ---- */

function renderModuleEditBar() { moduleEditBar.hidden = !moduleEditing; moduleEditName.textContent = moduleEditing ? moduleEditing.name : ""; viewport.classList.toggle("is-module-editing", !!moduleEditing); }
function clearModuleEdit() { moduleEditing = null; moduleEditBar.hidden = true; viewport.classList.remove("is-module-editing"); }
function beginModuleEdit(id) { const m = moduleLibrary.find((x) => x.id === id); if (!m) return; if (moduleEditing) { showToast(`正在编辑模块「${moduleEditing.name}」，请先「保存回模块」或「取消编辑」`); return; } const b = moduleBounds(m), c = viewportCenterWorld(); const px = clamp(c.x - b.x - b.w / 2, 10, Math.max(10, 2400 - b.w)), py = clamp(c.y - b.y - b.h / 2, 10, Math.max(10, 1500 - b.h)); const idMap = new Map(); const nodes = m.nodes.map((n) => { const nid = createId("node"); idMap.set(n.id, nid); return { id: nid, x: clamp(Math.round(px + n.x), 10, Math.max(10, 2400 - n.w)), y: clamp(Math.round(py + n.y), 10, Math.max(10, 1500 - n.h)), ...moduleNodeFields(n) }; }); const edges = m.edges.map((e) => ({ id: createId("edge"), from: idMap.get(e.from), to: idMap.get(e.to), ...normalizeEdgeFields(e) })).filter((e) => e.from && e.to); moduleEditing = { id: m.id, name: m.name, nodeIds: new Set(nodes.map((n) => n.id)) };
if (activeTool !== "select") setTool("select"); commit(() => { activeCanvas().nodes.push(...nodes); activeCanvas().edges.push(...edges); resetSelection(); selectedNodeIds = new Set(nodes.map((n) => n.id)); }, `模块「${m.name}」已打开，改完点「保存回模块」`); closeModuleModal(); }
function saveModuleEdit() { if (!moduleEditing) return; const m = moduleLibrary.find((x) => x.id === moduleEditing.id); if (!m) return clearModuleEdit(), showToast("原模块已不存在，编辑已退出"); const canvas = activeCanvas(); const nodes = canvas.nodes.filter((n) => moduleEditing.nodeIds.has(n.id)); if (!nodes.length) return showToast("模块内容已被删空。若确实想清空，请直接删除该模块；或先「取消编辑」"); const ids = new Set(nodes.map((n) => n.id)); const minX = Math.min(...nodes.map((n) => n.x)), minY = Math.min(...nodes.map((n) => n.y)); m.nodes = nodes.map((n) => ({ id: n.id, x: n.x - minX, y: n.y - minY, ...moduleNodeFields(n) })); m.edges = canvas.edges.filter((e) => ids.has(e.from) && ids.has(e.to)).map((e) => ({ from: e.from, to: e.to, ...normalizeEdgeFields(e) })); saveModules(); clearModuleEdit(); renderModules(); showToast(`模块「${m.name}」已更新（${m.nodes.length} 个节点、${m.edges.length} 条连线）`); }
function cancelModuleEdit() { if (!moduleEditing) return; const name = moduleEditing.name; clearModuleEdit(); render(); showToast(`已退出模块「${name}」的编辑，原模块未改动`); }

/* ---- 放置与封装 ---- */

function placeModule(module, x, y) { const idMap = new Map(); const nodes = module.nodes.map((n) => { const id = createId("node"); idMap.set(n.id, id); return { id, x: clamp(Math.round(x + n.x), 10, Math.max(10, 2400 - n.w)), y: clamp(Math.round(y + n.y), 10, Math.max(10, 1500 - n.h)), ...moduleNodeFields(n) }; }); const edges = module.edges.map((e) => ({ id: createId("edge"), from: idMap.get(e.from), to: idMap.get(e.to), ...normalizeEdgeFields(e) })).filter((e) => e.from && e.to); commit(() => { activeCanvas().nodes.push(...nodes); activeCanvas().edges.push(...edges); selectedNodeId = null; selectedEdgeId = null; connectorSourceId = null; resizeModeNodeId = null; selectedNodeIds = new Set(nodes.map((n) => n.id)); }, `模块「${module.name}」已放置`); nodes.forEach((n) => moduleEditing?.nodeIds.add(n.id)); }
function placeModuleAtCenter(moduleId) { const m = moduleLibrary.find((x) => x.id === moduleId); if (!m) return; const b = moduleBounds(m), c = viewportCenterWorld(); let px = c.x - b.x - b.w / 2 + modulePlaceOffset, py = c.y - b.y - b.h / 2 + modulePlaceOffset; px = clamp(px, 10, Math.max(10, 2400 - b.w)); py = clamp(py, 10, Math.max(10, 1500 - b.h)); modulePlaceOffset = (modulePlaceOffset + 40) % 240; placeModule(m, px, py); closeModuleModal(); }
function moduleBounds(module) { const minX = Math.min(...module.nodes.map((n) => n.x)), minY = Math.min(...module.nodes.map((n) => n.y)), maxX = Math.max(...module.nodes.map((n) => n.x + n.w)), maxY = Math.max(...module.nodes.map((n) => n.y + n.h)); return { x: minX, y: minY, w: maxX - minX, h: maxY - minY }; }
function viewportCenterWorld() { const r = viewport.getBoundingClientRect(), v = activeCanvas().view || { zoom: 1, panX: 0, panY: 0 }; return { x: (r.width / 2 - v.panX) / v.zoom, y: (r.height / 2 - v.panY) / v.zoom }; }
function saveSelectionAsModule() { const ids = currentSelectionNodeIds(); if (!ids.length) return showToast("请先框选或选中要封装的节点"); const canvas = activeCanvas(); const nodes = canvas.nodes.filter((n) => ids.includes(n.id)); if (!nodes.length) return showToast("没有可封装的节点"); const name = window.prompt("给这个模块起个名字（以后可按名字复用）", "流程模块"); if (!name?.trim()) return; const minX = Math.min(...nodes.map((n) => n.x)), minY = Math.min(...nodes.map((n) => n.y)), idSet = new Set(ids); const module = { id: createId("module"), name: name.trim(), createdAt: Date.now(), nodes: nodes.map((n) => ({ id: n.id, x: n.x - minX, y: n.y - minY, ...moduleNodeFields(n) })), edges: canvas.edges.filter((e) => idSet.has(e.from) && idSet.has(e.to)).map((e) => ({ from: e.from, to: e.to, ...normalizeEdgeFields(e) })) }; moduleLibrary.push(module); saveModules(); clearModuleEdit(); showToast(`模块「${module.name}」已保存（${module.nodes.length} 个节点、${module.edges.length} 条连线）`); }

/* ---- 删除、重命名与时间 ---- */

function deleteModule(id) { const m = moduleLibrary.find((x) => x.id === id); if (!m) return; if (moduleEditing?.id === id) return showToast(`模块「${m.name}」正在编辑中，请先「保存回模块」或「取消编辑」`); if (!window.confirm(`删除模块「${m.name}」？删除后无法恢复。`)) return; moduleLibrary = moduleLibrary.filter((x) => x.id !== id); saveModules(); renderModules(); showToast(`模块「${m.name}」已删除`); }
function renameModule(id) { const m = moduleLibrary.find((x) => x.id === id); const name = m && window.prompt("给模块起个新名字", m.name); if (!m || !name?.trim() || name.trim() === m.name) return; m.name = name.trim(); if (moduleEditing?.id === id) { moduleEditing.name = m.name; renderModuleEditBar(); } saveModules(); renderModules(); showToast("模块已重命名"); }
function formatModuleTime(ts) { if (!Number.isFinite(ts)) return ""; const d = new Date(ts), pad = (n) => String(n).padStart(2, "0"); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`; }
