/* ============================================================================
   节点卷（拆分自原 app.js，内容逐字照搬，未改一行逻辑）

   这一份文件管「画布上的一堆节点」：
     1. 节点增删——放置、居中放置、删除当前选择；
     2. 尺寸——渲染高度、内容高度、缩放控制点位置与类型、控制点渲染与清理；
     3. 就地编辑——双击 / 回车改名字的进入、提交、焦点判断；
     4. 拖拽缩放——按下 / 拖动 / 松手 / 取消四步。
   另含：标记样式类、选择态同步（节点高亮）——这两处被 node / inspector / marquee 共用，
   就近放在节点卷里。

   ⚠ 加载顺序：constants.js → storage.js → state.js → canvas.js → **本文件** → … → app.js
   本文件**只声明函数、不在顶层执行任何语句**，所以放在 app.js 之前即可；
   它调用 state.js 的 state / commit / pushHistory / popRollback、storage.js 的 markDirty / saveLocal、
   canvas.js 的 clampPan、app.js 的 render 等，都发生在被调用的那一刻，那时全部脚本都已加载完。
   ——反过来说：**往这里加顶层执行语句之前，先回来看这一段**。
   ============================================================================ */

/* ---- 节点渲染与尺寸 ---- */

function renderNodes() { commitPendingEdit(); if (typeof syncLinkingPorts === "function") syncLinkingPorts(); nodeLayer.innerHTML = ""; const canvas = activeCanvas(); canvas.nodes.forEach((node) => { const minimum = minSizeForType(node.type), isSelected = selectedNodeId === node.id, isResizeMode = resizeModeNodeId === node.id, el = document.createElement("div"); el.className = `node shape-${node.type}${isSelected ? " is-selected" : ""}${connectorSourceId === node.id ? " is-connecting" : ""}${selectedNodeIds.has(node.id) ? " is-in-selection" : ""}`; el.dataset.nodeId = node.id; el.tabIndex = 0; el.style.left = `${node.x}px`; el.style.top = `${node.y}px`; const nw = Math.max(node.w, minimum.w); el.style.width = `${nw}px`; if (node.type === "circle") { el.style.height = `${nw}px`; } else { el.style.minHeight = `${Math.max(node.h, minimum.h)}px`; } el.innerHTML = `<div class="node-content"><span class="node-label"></span><span class="node-note"></span><span class="node-marker"></span></div>`; el.querySelector(".node-label").textContent = node.label; el.querySelector(".node-note").textContent = node.note; el.querySelector(".node-marker").textContent = node.marker; el.querySelector(".node-marker").classList.add(markerClass(node.marker)); if (!node.note) el.querySelector(".node-note").hidden = true; const toggle = document.createElement("button"); toggle.type = "button"; toggle.className = `resize-toggle${isResizeMode ? " is-active" : ""}`; toggle.dataset.nodeId = node.id; toggle.title = isResizeMode ? "隐藏尺寸控制点" : "显示尺寸控制点"; toggle.setAttribute("aria-label", isResizeMode ? "隐藏尺寸控制点" : "显示尺寸控制点"); toggle.setAttribute("aria-pressed", String(isResizeMode)); toggle.hidden = !isSelected; toggle.innerHTML = `<span aria-hidden="true">⤢</span>`; el.append(toggle); const portDefs = node.type === "diamond" ? [["top", "进", ""], ["right", "否", "否"], ["bottom", "是", "是"], ["left", "未定", "未定"]] : [["top", "从上方连接", ""], ["right", "从右侧连接", ""], ["bottom", "从下方连接", ""], ["left", "从左侧连接", ""]]; portDefs.forEach(([side, label, branch]) => { const port = document.createElement("span"); port.className = "port"; port.dataset.side = side; port.title = label; if (branch) port.dataset.branch = branch; if (node.type === "diamond") { const lab = document.createElement("span"); lab.className = "port-label"; lab.textContent = label; port.append(lab); } el.append(port); }); nodeLayer.append(el); }); renderResizeHandles(canvas.nodes.find((node) => node.id === selectedNodeId)); document.querySelector("#canvasEmpty").hidden = canvas.nodes.length > 0; }
function markerClass(marker) { return `marker-${DISCUSSION_MARKERS.indexOf(marker) >= 0 ? DISCUSSION_MARKERS.indexOf(marker) : 0}`; }
function resizeHandlesForNode(node) { return Object.hasOwn(RESIZE_HANDLES_BY_TYPE, node.type) ? RESIZE_HANDLES_BY_TYPE[node.type] : RESIZE_HANDLES_BY_TYPE.rect; }
function nodeRenderHeight(node) { const el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(node.id)}"]`); return el && el.offsetHeight > node.h ? el.offsetHeight : node.h; } function nodeContentHeight(node) { const el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(node.id)}"]`); if (!el) return node.h; const prev = el.style.minHeight; el.style.minHeight = "0"; const h = el.offsetHeight; el.style.minHeight = prev; return h; } function resizeHandlePositions(node) { const h = nodeRenderHeight(node); return { nw: [node.x - 5, node.y - 5], n: [node.x + node.w / 2 - 5, node.y - 19], ne: [node.x + node.w - 5, node.y - 5], e: [node.x + node.w + 9, node.y + h / 2 - 5], se: [node.x + node.w - 5, node.y + h - 5], s: [node.x + node.w / 2 - 5, node.y + h + 9], sw: [node.x - 5, node.y + h - 5], w: [node.x - 19, node.y + h / 2 - 5] }; }
function renderResizeHandles(node) { if (!node || activeTool !== "select" || resizeModeNodeId !== node.id) return; const positions = resizeHandlePositions(node); resizeHandlesForNode(node).forEach((handle) => { const el = document.createElement("div"); el.className = `resize-handle resize-${handle}`; el.dataset.nodeId = node.id; el.dataset.handle = handle; el.title = "调整节点大小"; el.style.left = `${positions[handle][0]}px`; el.style.top = `${positions[handle][1]}px`; nodeLayer.append(el); }); }
function removeResizeHandles() { nodeLayer.querySelectorAll(".resize-handle").forEach((h) => h.remove()); }
function syncSelectionUI() { nodeLayer.querySelectorAll(".node").forEach((el) => { el.classList.toggle("is-selected", el.dataset.nodeId === selectedNodeId); el.classList.toggle("is-connecting", el.dataset.nodeId === connectorSourceId); el.classList.toggle("is-in-selection", selectedNodeIds.has(el.dataset.nodeId)); const toggle = el.querySelector(".resize-toggle"); if (toggle) toggle.hidden = el.dataset.nodeId !== selectedNodeId; }); }

/* ---- 节点增删 ---- */

function addNode(type, x, y) { if (activeCanvas().nodes.length >= MAX_NODES_PER_CANVAS) return showToast("节点数量已达上限，无法继续添加"); const p = screenToWorld(x, y), d = NODE_DEFAULTS[type], size = type === "diamond" || type === "circle" ? { w: 112, h: 112 } : type === "text" ? { w: 150, h: 48 } : type === "triangle" ? { w: 126, h: 112 } : { w: 176, h: 92 }, node = { id: createId("node"), type, x: Math.max(20, Math.min(p.x - size.w / 2, 2400 - size.w)), y: Math.max(20, Math.min(p.y - size.h / 2, 1500 - size.h)), ...size, label: d.label, note: d.note, marker: "待讨论", condition: "", exitCondition: "" }; commit(() => { activeCanvas().nodes.push(node); selectedNodeId = node.id; selectedNodeIds = new Set(); if (moduleEditing) moduleEditing.nodeIds.add(node.id); }, "节点已添加"); if (type === "text") beginEdit(node.id, true); }
function addNodeAtCenter(type) { const r = viewport.getBoundingClientRect(); addNode(type, r.left + r.width / 2, r.top + r.height / 2); }
function deleteSelection() { if (!selectedNodeId && !selectedEdgeId && !selectedNodeIds.size) return; const c0 = activeCanvas(); let question; if (selectedNodeIds.size) question = `删除已框选的 ${selectedNodeIds.size} 个节点？可通过撤销找回。`; else if (selectedNodeId) { const n = c0.nodes.find((x) => x.id === selectedNodeId); question = `删除节点「${n ? n.label : ""}」？可通过撤销找回。`; } else question = "删除这条连线？可通过撤销找回。"; if (!window.confirm(question)) return; commit(() => { const c = activeCanvas(); if (selectedNodeIds.size) { c.nodes = c.nodes.filter((n) => !selectedNodeIds.has(n.id)); c.edges = c.edges.filter((e) => !selectedNodeIds.has(e.from) && !selectedNodeIds.has(e.to)); selectedNodeIds = new Set(); } else if (selectedNodeId) { c.nodes = c.nodes.filter((n) => n.id !== selectedNodeId); c.edges = c.edges.filter((e) => e.from !== selectedNodeId && e.to !== selectedNodeId); } else c.edges = c.edges.filter((e) => e.id !== selectedEdgeId); selectedNodeId = null; selectedEdgeId = null; resizeModeNodeId = null; connectorSourceId = null; }, "已删除"); viewport.focus({ preventScroll: true }); }

/* ---- 就地编辑 ---- */

function focusInEditableControl() { const el = document.activeElement; if (!el) return false; if (el.isContentEditable) return true; const tag = el.tagName; if (tag === "INPUT") return !el.readOnly && !["checkbox", "radio", "button", "submit", "reset", "file"].includes(el.type); return tag === "TEXTAREA" || tag === "SELECT"; }
function commitPendingEdit() { if (!editing) return; const node = (editing.canvasId ? state.canvases.find((c) => c.id === editing.canvasId) : activeCanvas())?.nodes.find((n) => n.id === editing.nodeId); const el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(editing.nodeId)}"] .node-label`); let changed = false; if (node && el) { const label = ((el.innerText ?? el.textContent).trim() || "未命名节点").slice(0, 80); changed = node.label !== label; if (changed) { node.label = label; markDirty(); } } if (el) el.contentEditable = "false"; if (editing.token != null && !changed) popRollback(editing.token); editing = null; }
function beginEdit(id, noPush) { if (editing && editing.nodeId === id && editing.canvasId === state.activeCanvasId) return; commitPendingEdit(); const node = activeCanvas().nodes.find((n) => n.id === id), el = nodeLayer.querySelector(`[data-node-id="${CSS.escape(id)}"] .node-label`); if (!node || !el) return; const token = !noPush ? pushHistory() : null; editing = { nodeId: id, canvasId: state.activeCanvasId, before: node.label, token }; el.contentEditable = "true"; el.focus(); const range = document.createRange(); range.selectNodeContents(el); const sel = window.getSelection(); sel?.removeAllRanges(); sel?.addRange(range); }
function finishEdit(el) { if (!editing) return; const node = (editing.canvasId ? state.canvases.find((c) => c.id === editing.canvasId) : activeCanvas())?.nodes.find((n) => n.id === editing.nodeId); if (node) node.label = ((el.innerText ?? el.textContent).trim() || "未命名节点").slice(0, 80); const changed = !!node && node.label !== editing.before, token = editing.token, nodeId = editing.nodeId; el.contentEditable = "false"; editing = null; if (node) el.textContent = node.label; renderInspector(); updateStatus(); if (changed) saveLocal("文字已保存"); else if (token != null) popRollback(token); const nodeEl = nodeLayer.querySelector(`[data-node-id="${CSS.escape(nodeId)}"]`); if (refocusNodeAfterEdit) { refocusNodeAfterEdit = false; nodeEl?.focus(); } }

/* ---- 拖拽缩放 ---- */

function beginResize(e, nodeId, handle) { if (activeTool !== "select") return; const node = activeCanvas().nodes.find((item) => item.id === nodeId); if (!node) return; e.preventDefault(); e.stopPropagation(); resizing = { nodeId, handle, pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, originX: node.x, originY: node.y, originW: node.w, originH: nodeRenderHeight(node), originModelH: node.h, contentH: nodeContentHeight(node), changed: false, pushed: false, token: null }; viewport.setPointerCapture?.(e.pointerId); }
function updateResize(e) { if (!resizing) return; const node = activeCanvas().nodes.find((item) => item.id === resizing.nodeId), view = activeCanvas().view || { zoom: 1 }; if (!node) return; const dx = (e.clientX - resizing.startX) / view.zoom, dy = (e.clientY - resizing.startY) / view.zoom, handle = resizing.handle, minimum = minSizeForType(node.type), right = resizing.originX + resizing.originW, bottom = resizing.originY + resizing.originH; let x = resizing.originX, y = resizing.originY, w = resizing.originW, h = resizing.originH; if (handle.includes("e")) w = resizing.originW + dx; if (handle.includes("s")) h = resizing.originH + dy; if (handle.includes("w")) { w = resizing.originW - dx; x = resizing.originX + dx; } if (handle.includes("n")) { h = resizing.originH - dy; y = resizing.originY + dy; } if (w < minimum.w) { w = minimum.w; if (handle.includes("w")) x = right - w; } const contentH = resizing.contentH, minH = Math.max(minimum.h, contentH); if (h < minH) { h = minH; if (handle.includes("n")) y = bottom - h; } if (handle.includes("w")) w = Math.min(w, right - 10); else w = Math.min(w, Math.max(minimum.w, 2400 - resizing.originX)); if (handle.includes("n")) h = Math.min(h, Math.max(bottom - 10, minH)); else h = Math.min(h, Math.max(minimum.h, 1500 - resizing.originY)); if (handle.includes("w")) x = resizing.originX + resizing.originW - w; if (handle.includes("n")) y = resizing.originY + resizing.originH - h; let nw = Math.round(w), nh = Math.round(h); if (node.type === "circle") { nw = nh = Math.min(Math.max(nw, nh, minimum.w), 1490); if (handle.includes("w")) x = resizing.originX + resizing.originW - nw; if (handle.includes("n")) y = resizing.originY + resizing.originH - nh; } const nx = clamp(Math.round(x), 10, Math.max(10, 2400 - nw)), ny = clamp(Math.round(y), 10, Math.max(10, 1500 - nh)); const changed = nx !== resizing.originX || ny !== resizing.originY || nw !== resizing.originW || nh !== resizing.originH; if (changed && !resizing.pushed) { resizing.token = pushHistory(); resizing.pushed = true; } node.x = nx; node.y = ny; node.w = nw; node.h = Math.max(0, resizing.originModelH + (nh - resizing.originH)); resizing.changed = resizing.changed || changed; const resizeEl = nodeLayer.querySelector(`[data-node-id="${CSS.escape(node.id)}"]`); if (resizeEl) { const rw = Math.max(node.w, minimum.w); resizeEl.style.left = `${node.x}px`; resizeEl.style.top = `${node.y}px`; resizeEl.style.width = `${rw}px`; if (node.type === "circle") { resizeEl.style.height = `${rw}px`; } else { resizeEl.style.minHeight = `${Math.max(node.h, minimum.h)}px`; } } nodeLayer.querySelectorAll(".resize-handle").forEach((h) => h.remove()); renderResizeHandles(node); renderEdges(); markDirty(); }
function finishResize() { if (!resizing) return; const node = activeCanvas().nodes.find((item) => item.id === resizing.nodeId), unchanged = !!(node && node.x === resizing.originX && node.y === resizing.originY && node.w === resizing.originW && node.h === resizing.originModelH), changed = resizing.changed; if (resizing.pushed && unchanged) popRollback(resizing.token); resizing = null; render(); if (!unchanged && changed) saveLocal("节点大小已保存"); }
function cancelResize() { if (!resizing) return; const node = activeCanvas().nodes.find((item) => item.id === resizing.nodeId); if (node) { node.x = resizing.originX; node.y = resizing.originY; node.w = resizing.originW; node.h = resizing.originModelH; } const pushed = resizing.pushed, token = resizing.token; resizing = null; if (pushed) { popRollback(token); saveLocal("已取消调整大小"); } render(); }
